### ISSUE TITLE
[Question] webauthn - Utility of asking for $request

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-auth/webauthn-framework#1]
Looking through your library and noticed that you require a specific implementation for $request - a `Symfony\Component\HttpFoundation\Request` object - when doing FIDO2 client credential checking. Yet that object is not actually utilized in anything using `TokenBindingInterface`. Is this for future development?

I have an application that already has a PSR-7 `ServerRequestInterface` object (I'm using Zend Expressive middleware) and was wondering why you are asking for a Symfony-specific request object and not a PSR-7 object - especially since it's not really used anyways.

**Comment by moderndeveloperllc** [comment]
Thanks. This looks to be a great library for an exciting security technology. I look forward to using it in my future projects this year.

**Comment by Spomky** [comment]
I've just updated [the demo](https://github.com/web-auth/symfony-demo).
It is not finished, but you can already create a new account and use that new authentication process.

**Comment by Spomky** [comment]
The Psr7 interface `ServerRequestInterface` is now used by the library instead of the Symfony implementation.
The demo is also up to date.

**Comment by moderndeveloperllc** [comment]
Thanks. I know that made your tests a little more difficult, but it makes it so much easier for us non-Symfony folks. I'm going to to my best to actually provide pull requests and not just tickets for future items.

**Comment by Spomky** [comment]
Don’t worry about that. I usually prefer common interfaces instead of concrete implementations.
This is exactly what’s done in [another project](https://github.com/OAuth2-Framework/oauth2-framework)
