### ISSUE TITLE
Server Object Simplification

### ISSUE THREAD

**Issue by Spomky** [web-auth/webauthn-framework#101]
**Is your feature request related to a problem? Please describe.**
When a developer wants to create a server using the `Server` class, it is require to create a RelayingParty entity object and use it as argument. See [Webauthn\Server.php#L100](https://github.com/web-auth/webauthn-framework/blob/master/src/webauthn/src/Server.php#L100)

**Describe the solution you'd like**
It could be nice to directly set the rp data in the constructor.
Instead of the following lines:

```php
<?php

use Webauthn\Server;
use Webauthn\PublicKeyCredentialRpEntity;

$rpEntity = new PublicKeyCredentialRpEntity(
    'Webauthn Server',
    'my.domain.com'
);
$publicKeyCredentialSourceRepository = …;

$server = new Server(
    $rpEntity
    $publicKeyCredentialSourceRepository
);
```

We could have 

```php
<?php

use Webauthn\Server;

$publicKeyCredentialSourceRepository = …;

$server = new Server(
    'Webauthn Server',
    'my.domain.com',
    null, //Icon
    $publicKeyCredentialSourceRepository
);
```
**Describe alternatives you've considered**
As this change will induce a BC break, another way should be found.

**Additional context**
--NONE--

**Comment by moderndeveloperllc** [comment]
Your library of course, but saving one step doesn't seem worth it for a BC breaking change. I tend to just create the class in the server constructor. Oddly enough, I think it helps with the readability to keep it separate. Just having the RP entity info listed as params kinda looses that it's a part of the spec, etc.
```
$server = new Server(
    new PublicKeyCredentialRpEntity('Webauthn Server', 'my.domain.com');
    $publicKeyCredentialSourceRepository
);
```

**Comment by Spomky** [comment]
OK what you say makes sense so closing
