### ISSUE TITLE
Invalid signature: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by SeifertDaniel** [web-auth/webauthn-framework#103]
Hello Spomky,

I try to implement your webauthn package in our application using your new documentation https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-easy-way. Therefore I use the current version 2.1.7 of webauthn-lib.

Registration works fine, but login throws the exception "Invalid signature" in AuthenticatorAssertionResponseValidator class. Output from openssl_errorstring is "error:0906D06C:PEM routines:PEM_read_bio:no start line".
My test environment:
- Ubuntu Linux
- PHP 7.2

My tried keys are:
- Solo Key USB A
- Android Phone (7.1.1)

Both keys terminates in the same result.

The request object (base64 encoded):
eyJjaGFsbGVuZ2UiOiJxcVRaREwtOWJTSi1pZDZqVDRDSmgzUmxSRzZtajA4ZjBuVHdOSExBSmtFIiwicnBJZCI6Im94aWQ2NzIuZGFuaWVsLXNlaWZlcnQuY29tIiwidXNlclZlcmlmaWNhdGlvbiI6InByZWZlcnJlZCIsImFsbG93Q3JlZGVudGlhbHMiOlt7InR5cGUiOiJwdWJsaWMta2V5IiwiaWQiOiJMaVZWd1RXbWV1bnFhcGlHTGpzWGZjbUhSd1hjdk1kdVkzTWQ3WjllMEFIaWdPWGlmRkZJOUdBUlEzSlhudFVVIn0seyJ0eXBlIjoicHVibGljLWtleSIsImlkIjoiQWU1Tm10VjBwSHVna3FfcjVPZGtHT0tILTBnTjdmVEF2V3BiQzhEU0hvdDM0RGRCVTd0U3haMzFFV3NhRTVIOWVfWVJORVBERFZHOVR5MTN1VEtKRjZjIn1dLCJ0aW1lb3V0Ijo2MDAwMH0=

The  response object:
eyJpZCI6IkxpVlZ3VFdtZXVucWFwaUdManNYZmNtSFJ3WGN2TWR1WTNNZDdaOWUwQUhpZ09YaWZGRkk5R0FSUTNKWG50VVUiLCJ0eXBlIjoicHVibGljLWtleSIsInJhd0lkIjoiTGlWVndUV21ldW5xYXBpR0xqc1hmY21IUndYY3ZNZHVZM01kN1o5ZTBBSGlnT1hpZkZGSTlHQVJRM0pYbnRVVSIsInJlc3BvbnNlIjp7ImF1dGhlbnRpY2F0b3JEYXRhIjoiMjNjZVowS2R2cnRIRlVQc2ZDZVViOWNBWGl5bmp3SGdUWldERUlVZTFIb0JBQUFFSUE9PSIsImNsaWVudERhdGFKU09OIjoiZXlKamFHRnNiR1Z1WjJVaU9pSnhjVlJhUkV3dE9XSlRTaTFwWkRacVZEUkRTbWd6VW14U1J6WnRhakE0WmpCdVZIZE9TRXhCU210Rklpd2lZMnhwWlc1MFJYaDBaVzV6YVc5dWN5STZlMzBzSW1oaGMyaEJiR2R2Y21sMGFHMGlPaUpUU0VFdE1qVTJJaXdpYjNKcFoybHVJam9pYUhSMGNITTZMeTl2ZUdsa05qY3lMbVJoYm1sbGJDMXpaV2xtWlhKMExtTnZiU0lzSW5SNWNHVWlPaUozWldKaGRYUm9iaTVuWlhRaWZRPT0iLCJzaWduYXR1cmUiOiJNRVVDSVFEZUkxT3RlekpLeHJXbVErU0txaTJXUWptbEl6NkVGa0JnbnBXRStMdWVuQUlnQU9ZQU40ajhvSU9pV1BmNW9TNGl0RmRick1xYkt3TW43b2JFSERUcW5qRT0iLCJ1c2VySGFuZGxlIjpudWxsfX0=

Registration and login attempts on your demo page with the Solo Key work fine.

Do you have a suggestion? Please ask for further details, if required.

Thank you for your support.
Daniel.

**Comment by Spomky** [comment]
Hi Daniel,

At first sight it looks like the public key has an incorrect format.
Would you please share also the public key you store in your repository?

Thanks.

**Comment by SeifertDaniel** [comment]
Hello Florent,

thank you very much for your fast feedback.

I just discovered my mistake: Since I'm implementing the integration of the Webauthn package as a prototype first, I have the PublicKeyCredentialSource object and the corresponding PublicKeyCredentialSourceDescriptor object fixed in the source code instead of reading both from one database entry. Since I didn't know the key wrapping mechanism yet, both stored objects came from different registries and didn't have the same key ID. 

After regenerating both objects from the same registry, the login could now be checked successfully.

Now I can continue the integration.

Many greetings and best wishes,
Daniel.
