### ISSUE TITLE
Inconsistent usage of base64 encoding/decoding challenge

### ISSUE THREAD

**Issue by anita-tenjarla** [web-auth/webauthn-framework#104]
**Describe the bug**
First of all, thanks for the library! 

A small nit, but when setting up the library to register client keys, I noticed a disparity between the docs and the code. The [docs](https://github.com/web-auth/webauthn-framework/blob/master/doc/webauthn/PublicKeyCredentialCreation.md) suggest base64 _encoding_ the publicKeyCredential's `clientDataJSON` received from the client browser. This makes sense since one option for transmitting this data is through a url query parameter.

However, the `PublicKeyCredentialCreationOptions` object's [deserialization function](https://github.com/web-auth/webauthn-framework/blob/master/src/webauthn/src/PublicKeyCredentialCreationOptions.php#L142) will return a base64 _decoded_ challenge. This causes the relying party's registration comparison check to fail and was a bit difficult to debug as I anticipated things to just "work out of the box" after following the instructions.

**To Reproduce**
1. When kicking off a client's credential registration, create the `PublicKeyCredentialCreationOptions` object
2. [Serialize](https://github.com/web-auth/webauthn-framework/blob/master/src/webauthn/src/PublicKeyCredentialCreationOptions.php#L152) the `PublicKeyCredentialCreationOptions` object (as it needs to be stored in a php session) and store in session
3. Receive client's response, which has the `clientDataJSON` base64 encoded (this is encouraged in the docs and also has a very common use case)
3. Deserialize the `PublicKeyCredentialCreationOptions` object stored in client's php session for the `$authenticatorAttestationResponseValidator->check comparison` check
4. Encounter mismatch and [fail the attestation response check](https://github.com/web-auth/webauthn-framework/blob/master/src/webauthn/src/AuthenticatorAttestationResponseValidator.php#L67) 

**Expected behavior**
I expected registration to work after following the doc's instructions, and had to dig through the `PublicKeyCredentialCreationOptions.php` source code in order to debug my issue. I ultimately had to reimplement the `PublicKeyCredentialCreationOptions::createFromArray()` function in my own class to fix the behavior by removing the call to [base64 decode the challenge](https://github.com/web-auth/webauthn-framework/blob/master/src/webauthn/src/PublicKeyCredentialCreationOptions.php#L142).  

Again, this is a very minor issue. I thought it was worth reporting because it might help bolster WebAuthn adoption if configuration with this library "just worked" out of the box after following the readme's instructions.

**Potential fix**
Two potential fixes: 
1) Point out this potential base64 mismatch issue in the [docs](https://github.com/web-auth/webauthn-framework/blob/master/doc/webauthn/PublicKeyCredentialCreation.md)
2) Add a boolean parameter to the `PublicKeyCredentialCreationOptions.php::jsonSerialize()` and `PublicKeyCredentialCreationOptions::createFromArray()` functions to dictate whether or not to base64 encode the challenge.

I'm happy to make a PR for either option, but thought it was worth your consideration first since it's more of a design decision, or you might not consider this to even be an issue. 

Thanks again for writing this :) it's very well written and easy to follow!

**Comment by Spomky** [comment]
Hi @anita-tenjarla,

The documentation is being rewritten. You will find the first pages at https://webauthn-doc.spomky-labs.com/
The doc pages provided in this repository are not in line with the last version of the framework.
The JS script examples to correctly load the credentials options [can be found on this page](https://webauthn-doc.spomky-labs.com/pre-requisites/javascript).

It is planned to add complete examples for pure PHP scripts or using Symfony. Just need time for that...
I am sorry for the incovenience.

**Comment by anita-tenjarla** [comment]
No problem, thanks for the quick response! The new docs look great.

**Comment by Spomky** [comment]
Hi @anita-tenjarla,

I now close this issue as already answered.
Please note that the branch v3.0 have just been released and the doc at https://webauthn-doc.spomky-labs.com/ is in line with this new branch.

Regards

**Comment by mbursa** [comment]
I am still running into this issue using branch 4.0.
`PublicKeyCredentialCreationOptions` contains raw (decoded challenge).
When registering a client one loads the data received from the browser:
````
    $publicKeyCredential = $publicKeyCredentialLoader->loadArray($json_post_data);
    $publicKeyCredential->getResponse()->getClientDataJSON()->getChallenge()
````
The last line gets challenge in base64-encoded form, however, in `$authenticatorAttestationResponseValidator->check()` this is compared with `PublicKeyCredentialCreationOptions` (decoded) and it fails with 'Invalid challenge' error.
