### ISSUE TITLE
Windows Sign-In Options: Windows Hello PIN

### ISSUE THREAD

**Issue by Mazecreator** [web-auth/webauthn-framework#121]
I am not sure if "Windows Sign-In Options: PIN" is supported by the PHP Server Framework so I am adding this request as a Feature for now unless it can be confirmed it should work.

I am working with the PHP Server backend and the JavaScript front end without the use of Symfony Framework.  I am on the first step of learning and understanding the Creation of an account.

When I use an Android device with a finger print.  They code seems to work fine (or I am not seeing this exception thrown, but don't think that is the case).  

When I use my Windows 10 PRO PC with WIndows Hello PIN enabled.  I get the pop-up box for the PIN code after the first server response, but after I enter the PIN, the server throws the following exception.  While I don't see "type" passed as part of the object to the server, I also don't see "type" passed from the Android device.  I am not sure where that is provided to the "/PublicKeyCredentialLoader.php" script.  Is this a case where Windows doesn't support the proper encryption which is somehow detected internally after the following call:
`try {
    $publicKeyCredentialSource = $server->loadAndCheckAttestationResponse(
        $in,
        $publicKeyCredentialCreationOptions, // The options you stored during the previous step
        $serverRequest                       // The PSR-7 request
    );
`
This is the Exception thrown on the Windows system:

> Assert\InvalidArgumentException: The parameter "type" is missing in /home/iotmk/public_html/include/assert/lib/Assert/Assertion.php:2752 Stack trace:
> 
>  #0 /home/iotmk/public_html/include/assert/lib/Assert/Assertion.php(1256): Assert\Assertion::createException(Array, 'The parameter "...', 26, NULL, Array)
> 
>  #1 /home/iotmk/public_html/include/webauthn-framework-2.1.5/src/webauthn/src/PublicKeyCredentialLoader.php(54): Assert\Assertion::keyExists(Array, 'type', 'The parameter "...')
> 
>  #2 /home/iotmk/public_html/include/webauthn-framework-2.1.5/src/webauthn/src/PublicKeyCredentialLoader.php(80): Webauthn\PublicKeyCredentialLoader->loadArray(Array)
> 
>  #3 /home/iotmk/public_html/include/webauthn-framework-2.1.5/src/webauthn/src/Server.php(201): Webauthn\PublicKeyCredentialLoader->load('{"rawId":"u9TBB...')
> 
>  #4 /home/iotmk/public_html/attestation/result/index.php(107): Webauthn\Server->loadAndCheckAttestationResponse('{"rawId":"u9TBB...', Object(Webauthn\PublicKeyCredentialCreationOptions), Object(Nyholm\Psr7\ServerRequest))
> 
>  #5 {main}{"rp":{"name":"Greg Site Test","icon":"data:image\/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAMAAAC6V+0\/AAAAwFBMVEXm7NK41k3w8fDv7+q01Tyy0zqv0DeqyjOszDWnxjClxC6iwCu11z6y1DvA2WbY4rCAmSXO3JZDTxOiwC3q7tyryzTs7uSqyi6tzTCmxSukwi9aaxkWGga+3FLv8Ozh6MTT36MrMwywyVBziSC01TbT5ZW9z3Xi6Mq2y2Xu8Oioxy7f572qxzvI33Tb6KvR35ilwTmvykiwzzvV36\/G2IPw8O++02+btyepyDKvzzifvSmw0TmtzTbw8PAAAADx8fEC59dUAAAA50lEQVQYV13RaXPCIBAG4FiVqlhyX5o23vfVqUq6mvD\/\/1XZJY5T9xPzzLuwgKXKslQvZSG+6UXgCnFePtBE7e\/ivXP\/nRvUUl7UqNclvO3rpLqofPDAD8xiu2pOntjamqRy\/RqZxs81oeVzwpCwfyA8A+8mLKFku9XfI0YnSKXnSYZ7ahSII+AwrqoMmEFKriAeVrqGM4O4Z+ADZIhjg3R6LtMpWuW0ERs5zunKVHdnnnMLNQqaUS0kyKkjE1aE98b8y9x9JYHH8aZXFMKO6JFMEvhucj3Wj0kY2D92HlHbE\/9Vk77mD6srRZqmVEAZAAAAAElFTkSuQmCC","id":"iotmultikey.com"},"pubKeyCredParams":[{"type":"public-key","alg":-257},{"type":"public-key","alg":-259},{"type":"public-key","alg":-37},{"type":"public-key","alg":-39},{"type":"public-key","alg":-7},{"type":"public-key","alg":-36},{"type":"public-key","alg":-8}],"challenge":"hLh_X67nmI6uPckdNjw7iLSVdN3HGNkmWIa3GlsdOLY","attestation":"none","user":{"name":"user1.username","id":"MzkzMTc1NzQ0NTc4Mzk0MzgxOQ==","displayName":"user1.username"},"authenticatorSelection":{"requireResidentKey":false,"userVerification":"preferred"},"timeout":60000,"status":"ok"}'

**Comment by Spomky** [comment]
Hi,

Thank you for reporting me the troubles you have with the bundle. This is something I would like to simplify in a near future (see #116).

Few days ago, I created a very simple example based on a fresh SF 5.0 installation : https://github.com/web-auth/demo-symfony

It has only 2 commits. The first one corresponds to the installation of symfony. The second one includes all dependencies, the required services and a basic configuration.

I have no trouble with windows hello and pin codes. Have you tried the demo? It should work fine as well as the new demo I mentioned above.

Could you also send me the data returned by the authenticator and the options you created (JSON objects) The error seems to come from this input (maybe the content is not correctly encoded).

**Comment by Mazecreator** [comment]
Hi Spomky,

Strange, just tried the demo and it worked fine.  Here is some of the information collected:

Profile:
Username: user1.username
Creation date: 2020-03-06T18:47:37+00:00
Last login at:

Session:
Authenticator used:
vcbSsTmgZTtuy-HkPftOiyhoUh0835ReQGD5d6TnyuM
User was present: yes
User was verified: yes

Credentials:

ID:
vcbSsTmgZTtuy-HkPftOiyhoUh0835ReQGD5d6TnyuM
AAGUID: 00000000-0000-0000-0000-000000000000
Public Key: pAEDAzkBACBZAQC7Hr19GBr7lay0B_PLxtYixQiR0YH8JzTF-Vd2v71YaZIVM9G2a_YoNjtEAFmRJdqVKDRvV93X5qioTZyOBHyN9RR3_Z_eozHn5LHpiUIjL4vCHc-dPDVMwB54FPcegNBgboP0z0P-MUMWPQwOeh3wzFjIN9a9m0nLIEeaPTRFCAcyI_wKQyMuqGlYCEgGFM9rFmPhf4X6Kxk9KmBmgB87nsOKJJ4D08O4kxi-aGtO5jp147x0Vcvi1XwjAxZFfVviqhhUGU65izy49I6oVRVmkqYBB8lUMxW8N9CeVURIP1WMBQn3zQnk3w-CXU36x3vQah4pYPmyBKJlNoGK6t31IUMBAAE
Counter: 0
Attestation type: none
Trust path:
{}

I will look to see if my webauthn scripts are correct based upon the code I can see.  I have tried both of the following backend frameworks:
webauthn-framework-2.1.5
webauthn-framework-3.0

This was the raw input from the Authenicator that fails on my setup:

`{"rawId":"WsLeTCGuYi94YygfJG50xTfkF9wsxoDFEB1oXsnTf90","id":"WsLeTCGuYi94YygfJG50xTfkF9wsxoDFEB1oXsnTf90","response":{"clientDataJSON":"eyJjaGFsbGVuZ2UiOiJheVlTWkFaZWhSajZqSE9CWVlJd2szdC1CTGxCUEFpRVE0ODYzX1Jvc25BIiwiZXh0cmFfa2V5c19tYXlfYmVfYWRkZWRfaGVyZSI6ImRvIG5vdCBjb21wYXJlIGNsaWVudERhdGFKU09OIGFnYWluc3QgYSB0ZW1wbGF0ZS4gU2VlIGh0dHBzOi8vZ29vLmdsL3lhYlBleCIsIm9yaWdpbiI6Imh0dHBzOi8vaW90bXVsdGlrZXkuY29tIiwidHlwZSI6IndlYmF1dGhuLmNyZWF0ZSJ9","attestationObject":"o2NmbXRkbm9uZWdhdHRTdG10oGhhdXRoRGF0YVkBZ7rI6xIklbBBF3fmGgTGr3k7xcPMydXsXV1On-oaw1tlRQAAAAAAAAAAAAAAAAAAAAAAAAAAACBawt5MIa5iL3hjKB8kbnTFN-QX3CzGgMUQHWheydN_3aQBAwM5AQAgWQEAoglBDmLG4aOXgEBA_d87CeyXYC-F_0B7jFkKB8_ZBT3jtRYhhhWrIXZy3_edz6aSZjayB57h5Tp95-p2155i_vmHGbz_-04DFzuZKMTIUloOLa_hJWuZ06bQSLFSGJdGNgDRuuRNnkzOJGMEFyDUm_jBhBNhb1qAnbso4aEUBY7OG3bHvWrd4ZUKHCpw1WB6w2q9yBd0iCL3726jX74AETT-fQfqA7G0bBFALMj1Kg8Eb8zlm50Lwd7psH9ff93WRsI4aDMN4O6zY86SrmFe-6IAAS3mNOEkummkjviGyNGJzriFrEe0KWyKaikx1oQ9iCy2zfI8O8g2oMmXGoRx3SFDAQAB"}}`

**Comment by Mazecreator** [comment]
Just tried the code again on Android and it threw this Exception, must have missed it before.  So it doesn't seem to work with either device.  Any ideas what might be off?

**Comment by Spomky** [comment]
> Strange, just tried the demo and it worked fine.

I feel reassured. The problem may come from many reasons.
Could you please add a logger to your services to understand what is going on?

> This was the raw input from the Authenicator that fails on my setup:

Thank you for the data, but I also need the options to verify it.
Could you please generate new set of options/response?

**Comment by Mazecreator** [comment]
Okay, i wrote a quick longer interface for Psr/Logger... Not awesome and not formatted great, but dumps the message & array sent to the logger interface.  I have them in TXT files.  I only formatted the bottom by hand for the Exception.  I have also attached the input object back from the JavaScript interface (web client) as well as the global variables present for the session.  The options is in [PKCCO] towards the end of the globals.  Let me know if there is something I am missing.


[error_log_WebAuthn.txt](https://github.com/web-auth/webauthn-framework/files/4308419/error_log_WebAuthn.txt)
[globals.txt](https://github.com/web-auth/webauthn-framework/files/4308420/globals.txt)
[in_object.txt](https://github.com/web-auth/webauthn-framework/files/4308421/in_object.txt)

**Comment by Spomky** [comment]
Hi @Mazecreator,

Thank you for the log entries.
I figured out where the error comes from. The [`Credential` Interface](https://www.w3.org/TR/credential-management-1/#the-credential-interface) from the specification does not require the presence of the `type` parameter.

However, the FIDO Alliance tool used to verify the compliance of the library has a test that fails if this parameter is missing.

There is a contradiction here between the specification and the conformance tool.
If you try with the library v2.0.x, it should works fine as this test case is covered since v2.1.0.

I will open an issue to the FIDO Alliance repository to clarify that point.

Stay tuned.
Regards.

**Comment by Spomky** [comment]
Contrary to what I mentioned earlier, the spec [DOES require the `type` parameter](https://www.w3.org/TR/webauthn/#publickeycredential) with the value `public-key`.

It looks like the authenticator data you sibmet missed it.
Please have a look [at this demo](https://github.com/web-auth/demo-symfony/blob/master/templates/homepage/homepage.html.twig#L299-L307). The `type` parameter is set before it is sent to the Aerbauthn server.

I will check the documentation to be sure the provided JS doesn't miss it.

**Comment by Mazecreator** [comment]
Hi @Spomky ,

Okay, yes, it seemed like that parameter was missing but unsure where it got supplied and what it actually represented.  I was using this frontend:
https://github.com/apowers313/webauthn-yubiclone

It looks like the "type" was not included, I have hard coded it to "public-key" for now and will post a message on that github of the potential issue.  Hopefully it is that simple for now.

Thanks for your help.  I am going to close this issue.
