### ISSUE TITLE
Support ramsey/uuid ^4.0

### ISSUE THREAD

**Issue by reedy** [web-auth/webauthn-framework#124]
4.0.0/4.0.1 of ramsey/uuid have been released

https://github.com/ramsey/uuid/releases/tag/4.0.0
https://github.com/ramsey/uuid/releases/tag/4.0.1

**Comment by reedy** [comment]
https://github.com/web-auth/webauthn-framework/pull/122 has tried to do this automatically....

**Comment by Spomky** [comment]
#122 simply change ^3.8 into ^4.0.
I will change that to allow both ^3.8 and ^4.0 if possible otherwise this will be part of the next major release

**Comment by Spomky** [comment]
Fixed in the new branch 3.2
