### ISSUE TITLE
Treat localhost as secure context

### ISSUE THREAD

**Issue by jakobbraun** [web-auth/webauthn-framework#125]
For development it would be very helpful to treat localhost as secure context (like suggested [here](https://www.w3.org/TR/secure-contexts/#localhost)).

Right now I get the error message `Invalid scheme. HTTPS required.` on attestation response verification.

**Comment by Spomky** [comment]
Agreed.

To avoid any security issue, the RP IDu (i.e. the domains) allowed to be used without https shall be explicitly defined.
I  will add an optional argument for that purpose.

**Comment by Spomky** [comment]
Fixed in the new branch 3.2
