### ISSUE TITLE
Fetching the information about authenticator transport method

### ISSUE THREAD

**Issue by rublon-mra** [web-auth/webauthn-framework#130]
Hello,
In my opinion the library should fetching the information about authenticator transport method, e.g. usb, internal. 
Currently, method loadAndCheckAttestationResponse() from Server class always returns empty array in transports field.
In my application I need this information to distinguish between devices registered with USB and using Windows Hello function in Windows 10.
Can I block the possibility of registration using Windows Hello function where only the PIN of my Microsoft user account is required for authentication?

Kind regards,
Matthew

**Comment by Spomky** [comment]
Hi @astec-mra,

There are 2 possibilities to solve that.

Authenticators are separated into 2 groups: [Roaming and Platform authenticators](https://webauthn-doc.spomky-labs.com/webauthn-in-a-nutshell/authenticators). To prevent any roaming authenticators to be used (i.e. USB/NFC/BLE ones), you can set the [attachment modality](https://webauthn-doc.spomky-labs.com/deep-into-the-framework/authenticator-selection-criteria#authenticator-attachment-modality) to `AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_PLATFORM`. This way no USB/NFC/BLE devices can be used.

The first solution is quite simple and easy to implement, but it still allows other roaming authenticators than W10 to be used (e.g. Android based smartphones). If you want to restrict the use of you application to a limited set of authenticators, you will need the [Attestation feature](https://webauthn-doc.spomky-labs.com/deep-into-the-framework/attestation-and-metadata-statement) and a custom Attestation Repository providing [the AAGUIDs listed in this page](https://docs.microsoft.com/en-us/microsoft-edge/dev-guide/windows-integration/web-authentication#special-considerations-for-windows-hello).
Unfortunately I don't know where to find the Attestation Medatada associated to those AAGUIDs and, AFAIK, the MDS service from the Fido Alliance does not list them at the moment.

As the Metadata Statement services are not mature enough (some specifications are ongoing), I think the library could allow missing statement in some cases. I will consider that in the next major release.

**Comment by rublon-mra** [comment]
@Spomky Thank you for the information. Everything seems clear now :)
