### ISSUE TITLE
[4.0] Test helpers

### ISSUE THREAD

**Issue by DarkGhostHunter** [web-auth/webauthn-framework#139]
I'm always frustrated when I try to mock a WebAuthn response from a virtual device. There is no library or something to return a WebAuthn response from a device for attestation and assertion and test the application flow.

**Describe the solution you'd like**
Test helpers.
```php

$response = $this->createAssertionResponse($options, [
    // ... Authenticator response parameters
]);

$response = $this->createAttestationResponse($options, [
    // ... Authenticator response parameters
]);
```

This way we can use the package to integrate it to other frameworks or even vanilla PHP code.

**Describe alternatives you've considered**
There are none.

**Additional context**
The other solution is to simply use real authentication data which may become a security flaw in the road.

**Comment by Spomky** [comment]
Hi @DarkGhostHunter,

Thank you for this idea.
I am not sure to understand what you expect here. Why don't you just [mock the reponse like here](https://github.com/web-auth/webauthn-framework/blob/3904e58b8f63e3c1a9acf1e3fdc911736a355ff9/src/webauthn/tests/unit/AuthenticatorAssertionResponseTest.php#L34-L42)? (test to be improved by the way...)

**Comment by DarkGhostHunter** [comment]
Mainly because I wanted to check if the credentials where persisted correctly. These are transformed once these reach he database for storage purposes.

Since the public key is a bunch of binary code, being able to retrieve it and check against an assertion is impossible unless I mount an application and start checking manually.

**Comment by Spomky** [comment]
I understand your concerns, but how could this framework be able to manage integration tests from othet applications?
Do you think a dedicated trait could be added?

**Comment by DarkGhostHunter** [comment]
Yes, that should be enough. That allows to mock an authenticator response, and check how to proceed if, for example, the validator pushes a response that is not expected to the application, hence, the framework.
