### ISSUE TITLE
[4.0] Framework arquitecture

### ISSUE THREAD

**Issue by DarkGhostHunter** [web-auth/webauthn-framework#141]
After using the framework, seems that there are a lot of caveats and nuances the framework in its current states has:

* Using the `beberley/assert` unnecessary. 
* Errors made by the framework should extend a common identifiable interface, like `WebAuthnValidationException`.
* Excessively large class names.
* Validation serial flow should use [Matryoshka-pipelines](https://medium.com/swlh/laravel-the-hidden-pipeline-part-1-a4ae91fc55a4), which makes it more maintainable in the long run.
* Excessively large construction arguments for some classes.
* Validators are require repository operations, making impossible to test separately.
* And also the HTTP Request itself (why is this mandatory?).
* A lot of DRY violations that could be wrapped into a common class, like Jsonable classes.

I've spent a lot of time with the framework and it's fucking obnoxious on some parts. I think the `easy` way is cool and good enough as long it unifies the tasks into single easy-to-understand methods, as long it only encapsulates different tasks instead of keeping a class doing multiple things.

/rant

**Comment by Spomky** [comment]
Hi @DarkGhostHunter,

Thank you for this feedback. I will try to run into it ste by step as it contains a lot of suggestions/advices

> Using the beberley/assert unnecessary.
> Errors made by the framework should extend a common identifiable interface, like WebAuthnValidationException.

I partially agree with you.
It is ok to introduce custom exceptions so that Webauthn errors can be correctly managed.
For assertions at the beginning of the classes, they are all part dedicated to a sanity check. I don't see any problem with the dependency. Please note that when the minimal PHP version will be 7.4, most (all?) of the property/argument types will be typed-hinted so some assertions will be removed.

> Excessively large class names.

This reason for that is that [all the names in the framework](https://webauthn-doc.spomky-labs.com/#class-constant-and-property-names) directly come from the specification.
Anyhow, if you have examples for which names could be improved, I may reconsider that rule.

> Validation serial flow should use Matryoshka-pipelines, which makes it more maintainable in the long run.

I don't know this flow. Let me dig into it first.

> Excessively large construction arguments for some classes.

It is ok to remove optional arguments from constructors and set them with a dedicated function.

> Validators are require repository operations, making impossible to test separately.

I am not sure to understand. You should be able to mock all arguments so this should not be a problem for your tests.

> And also the HTTP Request itself (why is this mandatory?).

Only the host and the token binding ID (if present) are required.
This can be changed and passed via arguments.

>  A lot of DRY violations that could be wrapped into a common class, like Jsonable classes.

OK I am opened to any suggestions for that point.

> I've spent a lot of time with the framework and it's fucking obnoxious on some parts. I think the easy way is cool and good enough as long it unifies the tasks into single easy-to-understand methods, as long it only encapsulates different tasks instead of keeping a class doing multiple things.

For sure this framework can be improved at several parts.
You may have missed it, but I am alone maintaining this framework, writting the doc and so on.
All contributions, sponsors or feedbacks like this one are welcome.

**Comment by Spomky** [comment]
> Excessively large construction arguments for some classes.

WIP. Please see #142

Eample with `Webauthn\PublicKeyCredentialCreationOptions`:

```php
//v3.x
public function __construct(PublicKeyCredentialRpEntity $rp, PublicKeyCredentialUserEntity $user, string $challenge, array $pubKeyCredParams, ?int $timeout = null, array $excludeCredentials = [], ?AuthenticatorSelectionCriteria $authenticatorSelection = null, ?string $attestation = null, ?AuthenticationExtensionsClientInputs $extensions = null)

//v4.0
public function __construct(PublicKeyCredentialRpEntity $rp, PublicKeyCredentialUserEntity $user, string $challenge, array $pubKeyCredParams)
```

Chained calls will be possible from v3.3:

```php
$options = PublicKeyCredentialCreationOptions::create($rp, $userEntity, $challenge, $credentialParams)
    ->excludeCredentials($excludeCredentials)
    ->setAuthenticatorSelection($authenticatorSelection)
    ->setAttestation($attestationConveyance)
    ->setExtensions($authenticationExtensionsClientInputs)
    ->setTimeout(30000)
;
```

**Comment by DarkGhostHunter** [comment]
> Hi @DarkGhostHunter,
> 
> Thank you for this feedback. I will try to run into it ste by step as it contains a lot of suggestions/advices
> 
> > Using the beberley/assert unnecessary.
> > Errors made by the framework should extend a common identifiable interface, like WebAuthnValidationException.
> 
> I partially agree with you.
> It is ok to introduce custom exceptions so that Webauthn errors can be correctly managed.
> For assertions at the beginning of the classes, they are all part dedicated to a sanity check. I don't see any problem with the dependency. Please note that when the minimal PHP version will be 7.4, most (all?) of the property/argument types will be typed-hinted so some assertions will be removed.

PHP minimum version will be 7.4 after 6th december 2021. There is still a long way that to happen.

My point is that There are validation exceptions, and code errors. The first I think should be clearly identifiable and separated from developer-problems.

> 
> > Excessively large class names.
> 
> This reason for that is that [all the names in the framework](https://webauthn-doc.spomky-labs.com/#class-constant-and-property-names) directly come from the specification.
> Anyhow, if you have examples for which names could be improved, I may reconsider that rule.

I have a list, but basically remove eveything that starts with "PublicKey".

> > Validation serial flow should use Matryoshka-pipelines, which makes it more maintainable in the long run.
> 
> I don't know this flow. Let me dig into it first.

Basically you send an object through many classes. The classes modify the result, but in this case, is just separation. The list of classes is an array, so you can add or even disable them ar runtime.

> > Excessively large construction arguments for some classes.
> 
> It is ok to remove optional arguments from constructors and set them with a dedicated function.

Yes, but from my perspective, we can just use a polymorphic class. [I did one sometime ago to avoid this problem](https://github.com/DarkGhostHunter/Fluid).

> > Validators are require repository operations, making impossible to test separately.
> 
> I am not sure to understand. You should be able to mock all arguments so this should not be a problem for your tests.
>
> > And also the HTTP Request itself (why is this mandatory?).
> 
> Only the host and the token binding ID (if present) are required.
> This can be changed and passed via arguments.


For example, the validator for assertion requires the repository to check for the counter. So both logics are tied. If I mock the Validator, I will need a 100% valid assertion response. The Server Request interface is required for checking the host. A whole class for only the Request Host uri.

Some dependencies are unnecesary, IMO. There are a lot of logics that can be separated into their own without depending on others, and leave the whole one-method-one-result logic to the Easy way.


> > A lot of DRY violations that could be wrapped into a common class, like Jsonable classes.
> 
> OK I am opened to any suggestions for that point.
 
I saw a lot of classes that can be serialized into JSON. [I solved it with this](https://github.com/DarkGhostHunter/Fluid). I think something similar could be done here.

> > I've spent a lot of time with the framework and it's fucking obnoxious on some parts. I think the easy way is cool and good enough as long it unifies the tasks into single easy-to-understand methods, as long it only encapsulates different tasks instead of keeping a class doing multiple things.
> 
> For sure this framework can be improved at several parts.
> You may have missed it, but I am alone maintaining this framework, writting the doc and so on.
> All contributions, sponsors or feedbacks like this one are welcome.

I think this could be more maintanable by separating and modularizing more each section of the framework. This is already done, but the next step is take out the dependencies to allow the developer how an when to proceed.

There is a lot of verbose code, which makes this package difficult to maintain from other developer perspective. Simplifying these would open it more to others to edit without pouring days understanding what does what and why.

> Chained calls will be possible from v3.3:

Okay, but but the values by by chained calls should have default values when not set, otherwise it should be mandatory.
