### ISSUE TITLE
Origin verification

### ISSUE THREAD

**Issue by thexeos** [web-auth/webauthn-framework#143]
For both, registration and verification, the following step is required:

> Verify that the value of C.origin matches the Relying Party's origin.

Implementations are located here: [registration](https://github.com/web-auth/webauthn-framework/blob/7f041067f4c4225dd92aca6175d6a8b37ae8ee1b/src/webauthn/src/AuthenticatorAttestationResponseValidator.php#L112) and [verification](https://github.com/web-auth/webauthn-framework/blob/7f041067f4c4225dd92aca6175d6a8b37ae8ee1b/src/webauthn/src/AuthenticatorAssertionResponseValidator.php#L151)

In both cases the verification is performed on the suffix of the origin:

     Assertion::eq(mb_substr($clientDataRpId, -$rpIdLength), $facetId, 'rpId mismatch.');

Which allows `evilexample.com` to pass the verification as `example.com`, which should fail according to [the specs](https://www.w3.org/TR/webauthn/#rp-id):

> The RP ID must be equal to the origin's effective domain, or a registrable domain suffix of the origin's effective domain.

Which links to [steps to perform the domain suffix check](https://html.spec.whatwg.org/multipage/origin.html#is-a-registrable-domain-suffix-of-or-is-equal-to).

This means that two checks are required: first an exact match, then a suffix match.

Since `$facetId` is treated as a domain, we can handle this in one assertion:

    $rpIdLength = mb_strlen($facetId);
    Assertion::eq(mb_substr('.' . $clientDataRpId, -($rpIdLength + 1)), '.' . $facetId, 'rpId mismatch.');

Potential problem with this is if the user specifies an invalid `id` (in RP that they pass) by prepending the period themselves (`id: ".example.com"`). But since that makes the RP ID invalid according to specs, I think it can be safely ignored.

Also, I can't see how this can be a vector, as user agents (should) enforce the same-origin policy.

**Comment by Spomky** [comment]
Thank you. This is now fixed in v3.2.8.

Best regards
