### ISSUE TITLE
[3.x] Update CBOR dependency to 2.0

### ISSUE THREAD

**Issue by DarkGhostHunter** [web-auth/webauthn-framework#144]
As title says. It should work without any problems for the framework. I think is safe to put `^1.0.2||^2.0.0`.

**Comment by Spomky** [comment]
Hi @DarkGhostHunter,

Thank you for the reminder. This will be done soon.

Regards

**Comment by Spomky** [comment]
Closing as done in v3.3 branch that will be released soon.
Many thanks
