### ISSUE TITLE
When jsonSerialize() CreationOptions, encode user entity as well

### ISSUE THREAD

**Issue by srigi** [web-auth/webauthn-framework#145]
**Is your feature request related to a problem? Please describe.**
When sending credential CreationOptions to the client, lib calls `$publicKeyCredentialCreationOptions->jsonSerialize()`. This encode `challenge` into base64. However, in mine implementation I'm storing a resident key `PublicKeyCredentialUserEntity::id`. It is a UUID in a binary form. jsonSerialize() is not encoding this binary data for the client!

**Describe the solution you'd like**
Call `->jsonSerialize()` on user, in this exact place: https://github.com/web-auth/webauthn-framework/blob/7f041067f4c4225dd92aca6175d6a8b37ae8ee1b/src/webauthn/src/PublicKeyCredentialCreationOptions.php#L162

**Comment by Spomky** [comment]
Hi @srigi,

The user ID [should be encoded as well](https://github.com/web-auth/webauthn-framework/blob/7f041067f4c4225dd92aca6175d6a8b37ae8ee1b/src/webauthn/src/PublicKeyCredentialUserEntity.php#L81).

From what I see,
* If we call `json_encode($options)`, the ID is correctly encoded.
* If we call `$options->jsonSerialize()`, the ID is won't be encoded.

I will update the library and make sure `->jsonSerialize()` is always called for all classes that implement the `\JsonSerializable` interface.

**Comment by Spomky** [comment]
Closing as work is in progress in #147.
Let’s continue the discussion in the PR thread.
