### ISSUE TITLE
[3.x] Documentation of User Authentication is Outdated/Wrong

### ISSUE THREAD

**Issue by m33x** [web-auth/webauthn-framework#150]
**Describe the bug**
The documentation says one needs to call `authenticatorAssertionResponse->check()` to authenticate a user. However, the class `authenticatorAssertionResponse` does not offer a `check()` function, instead it needs to be the `authenticatorAssertionResponseValidator` class.

**To Reproduce**
1. Go to [the current documentation](https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-hard-way/authenticate-your-users) and compare the call `$authenticatorAssertionResponse->check()` with `$authenticatorAssertionResponseValidator->check()` in the [outdated version 2.1 documentation](https://github.com/web-auth/webauthn-framework/blob/v2.1/doc/webauthn/PublicKeyCredentialRequest.md). 

**Expected behavior**
It should be `$authenticatorAssertionResponseValidator->check()`.

**Comment by Spomky** [comment]
Good catch! This is now fixed.
You may have missed it, but you can propose modifications directly from the documentation. Anyway I really appreciate any comment/typo reports.

Thank you.
Regards.
