### ISSUE TITLE
Certificate problem in unit tests

### ISSUE THREAD

**Issue by szepeviktor** [web-auth/webauthn-framework#152]
**Describe the bug**
There are failing [unit tests](https://github.com/web-auth/webauthn-framework/blob/3904e58b8f63e3c1a9acf1e3fdc911736a355ff9/src/webauthn/tests/functional/AttestationStatementWithTokenBindingTest.php#L41)
https://travis-ci.org/github/web-auth/webauthn-framework/jobs/714186359#L240

Could you start me up to fix them?

**Comment by szepeviktor** [comment]
Please help.

**Comment by Spomky** [comment]
Hi @szepeviktor,

I've just pinned that issue to prevent stale from closing it.
THis is definitively something that will be addressed.
Nevertheless, it requires some modifications first and I need time to do it.

**Comment by Spomky** [comment]
Closing as we now use Github Actions in favour of Travis-CI

**Comment by szepeviktor** [comment]
I understand.
Hype vs. mature product.
