### ISSUE TITLE
Authenticator assertion does not check user present (UP) flag [section 7.2.12]

### ISSUE THREAD

**Issue by anita-tenjarla** [web-auth/webauthn-framework#153]
**Describe the bug**
The authenticator assertion logic does not check if User Present (UP) flag is set. According to the [webauthn spec](https://www.w3.org/TR/webauthn/#verifying-assertion), section 7.2.12 says:

> 12. Verify that the User Present bit of the flags in authData is set.

However, in code (as best as I can tell) this step is skipped (https://github.com/web-auth/webauthn-framework/blob/v3.2/src/webauthn/src/AuthenticatorAssertionResponseValidator.php#L162) and proceeds to step 7.2.13 to check for the User Verification (UV) flag. 

**To Reproduce**
1. Using webauthn-framework, login with security key
2. View GetAssertion response from authenticator
3. User Presence flag is unset but login is accepted (in other words, the check() function in class AuthenticatorAssertionResponseValidator does not throw an error)

**Expected behavior**
If User Presence flag is unset, then check() function in AuthenticatorAssertionResponseValidator class should throw an error.

**Desktop:**
I believe all

**Smartphone:**
I believe all

**Additional context**
I notice that for Attestation the UP flag is checked in metadata, but I could not find similar logic for Assertion. However I might've missed it to please correct me if I did. Thank you so much!

**Comment by anita-tenjarla** [comment]
Woah that was quick, thanks so much!

**Comment by Spomky** [comment]
Hi @anita-tenjarla,

Thank you for this issue. I have just merged the PR #154 and tagged `v3.2.9` to fix it.
