### ISSUE TITLE
Allowing adding webauthn authentication to existing user 

### ISSUE THREAD

**Issue by jmalinens** [web-auth/webauthn-framework#156]
This is more like support request from me.
I am using Symfony bundle and there are 2 route groups:

* /register (it creates new user with webauthn)
* /login (it logins user with webauthn)

If there is existing user database there should be 3rd option:
* /add_webauthn

which would enable adding webauthn authentication to existing users.

I can not use /register endpoint as there is check in src/Security/Firewall/CreationListener.php:

```php
Assertion::null($userEntity, 'Invalid username');
```
which fail if such user already exists (is not null).

I am trying to figure out best way to implement 3rd option but I am little bit stuck.

I am thinking about reusing `/register/options` for 1st request and create separate route something like `/add_webauthn` instead of `/register`

Thank You for the library!

**Comment by Spomky** [comment]
Hi @jmalinens,

This feature is described in the documentation at https://webauthn-doc.spomky-labs.com/v/v3.0/deep-into-the-framework/register-authenticators (lots of typos here ; this page should be updated…).
With the next minor release 3.3, this feature will be  directly supported using simple configuration options. (see https://webauthn-doc.spomky-labs.com/v/v3.3/deep-into-the-framework/register-authenticators)

**Comment by jmalinens** [comment]
@Spomky  closing issue as https://webauthn-doc.spomky-labs.com/v/v3.0/deep-into-the-framework/register-authenticators was exactly what I wanted
