### ISSUE TITLE
webauthn-symfony-bundle: id field of PublicKeyCredentialUserEntity

### ISSUE THREAD

**Issue by digitalshow** [web-auth/webauthn-framework#157]
I want to add Webauthn support to my Symfony application. I have an existing user entity with a numeric id field. If I get it right the webauthn-symfony-bundle forces me to use PublicKeyCredentialUserEntity as a base class for my user entities. Now that class defines the id field containing the user handle, but my class already has an id field. 

[Here](https://github.com/web-auth/webauthn-framework/issues/36#issuecomment-472164021) you don't suggest using the user handle as a primary key. Now what is your suggestion to implement the user entity? Am I missing something? I think it would be a good option to use an interface for the user in the Security classes that only has a method to get a PublicKeyCredentialUserEntity object from a user entity. That way it would be much easier to allow for custom implementations.

**Comment by Spomky** [comment]
Hi @digitalshow,

No you are not forced to extend any class for your Symfony application.

What you should do is to:
* add a new property to your current user entity (let say `webauthnId`). This property shall be a string and unique.
* add a new method that will return the associated `PublicKeyCredentialUserEntity` object.

Next, you can create a repository that implements `Webauthn\Bundle\Repository\PublicKeyCredentialUserEntityRepository` (or implement it to an existing one) and add a query that will use this new property.

[EDIT]: maybe I should write some words about that in the documentation.

**Comment by digitalshow** [comment]
Hi @Spomky,

thanks for the explanation. When I do that, how will Symfony know of my user entity after login? Won't Symfony use the `PublicKeyCredentialUserEntity` as the user so my own user entity will effectively not be used?

**Comment by Spomky** [comment]
The firewall will find the `PublicKeyCredentialUserEntity` during the authentication ceremony.
Both this object and the Symfony UserInterface have the same unique information: the username.
Your Symfony user will be retrieved [during the authentication process using the User Provider and its username](https://github.com/web-auth/webauthn-framework/blob/v3.2/src/symfony/src/Security/Authentication/Provider/WebauthnProvider.php#L49).
If everything went fine, the [Symfony user is associated to the token](https://github.com/web-auth/webauthn-framework/blob/v3.2/src/symfony/src/Security/Authentication/Provider/WebauthnProvider.php#L71).

**Comment by Spomky** [comment]
Closing as answered.
Feel free to open it again if deemed necessary.
