### ISSUE TITLE
[Symfony] Non scalar value in extensions

### ISSUE THREAD

**Issue by leonelvsc** [web-auth/webauthn-framework#162]
**Is your feature request related to a problem? Please describe.**
As the RFC states https://www.w3.org/TR/webauthn/#sctn-authenticator-biometric-criteria-extension , that extension is a dictionary ( assoc array in php ).

When Symfony process the configuration of the bundle it expects a scalar value
![DeepinScreenshot_select-area_20201214141922](https://user-images.githubusercontent.com/2332029/102113142-6edbca80-3e17-11eb-94cb-a9a0157ad8c1.png)

**Describe the solution you'd like**
The possibility of declare the extension like this
![DeepinScreenshot_select-area_20201214141720](https://user-images.githubusercontent.com/2332029/102112982-3e942c00-3e17-11eb-95d5-061944660c71.png)

**Comment by Spomky** [comment]
Hi @leonelvsc,

Thank you for reporting this issue.
A patch was applied and this should be fixed with `v3.2.11`.

**Comment by leonelvsc** [comment]
In `Configuration.php` line `213` it's still on `scalarPrototype`, that option just applies to the creation profile?, i ask because i don't have a full knowledge of the webauthn framework

**Comment by Spomky** [comment]
Hi @leonelvsc,

I forgot answering your question.
You are right absolutely. The [line 213](https://github.com/web-auth/webauthn-framework/blob/v3.2/src/symfony/src/DependencyInjection/Configuration.php#L213) has also been changed to accept arrays. This change is shipped with `v3.2.12`

Regards.

**Comment by leonelvsc** [comment]
This was deprecated from standard i see, is there any way of force biometric authenticator and disable ie: PIN authenticator?

**Comment by Spomky** [comment]
Hi, 

The UVM extension seems to be a possible solution for your use case.
Have a look at this page https://www.w3.org/TR/webauthn-2/#sctn-uvm-extension
