### ISSUE TITLE
Php 8 compatibility

### ISSUE THREAD

**Issue by ChristophWurst** [web-auth/webauthn-framework#164]
**Is your feature request related to a problem? Please describe.**

Nextcloud is preparing for php8. We're looking at our dependencies and make sure we update/fix the ones that are not ready for php8. ``web-auth/webauthn-lib`` is one of them.

**Describe the solution you'd like**

Fix any php8 incompatibility and declare php8 as compatible via composer.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

**Comment by ChristophWurst** [comment]
Fixed for v3.3 apparently https://github.com/web-auth/webauthn-framework/pull/165#issuecomment-752743617

**Comment by Spomky** [comment]
Hi @ChristophWurst,

V3.3 has been released. Please start with `v3.3.1` to have full compatibility with PHP8.
Do not hesitate to warn me if something went wrong with this new branch.

BR.

**Comment by ChristophWurst** [comment]
It seems to work flawless so far. Thanks a lot :v:
