### ISSUE TITLE
web-auth/cose-lib requires "beberlei/assert": "^3.2" => No PHP 8 support

### ISSUE THREAD

**Issue by ildyria** [web-auth/webauthn-framework#168]
**Describe the bug**
`web-auth/cose-lib` requires `"beberlei/assert": "^3.2"`

As stated in `beberlei/assert` version 3.2.7 (maximum possible given the composer.json) only support PHP 7.

`beberlei/assert` version 3.3.1 supports PHP 7 and PHP 8.

**Comment by Spomky** [comment]
Hi @ildyria,

I am not sure to clearly understand the issue. With the rule "^3.2", the version 3.3.x can be installed.

**Comment by jdreesen** [comment]
`^3.2` allows installation of `3.3.1`.

**Comment by ildyria** [comment]
Hi @jdreesen @Spomky. First of all, thank you for your prompt answer. :+1: 

Hummm. :thinking:

**Comment by ildyria** [comment]
I will try to understand why it is locked to version 3.2.7 then. Something weird is going on with my composer. Thanks.

**Comment by Spomky** [comment]
Maybe another dep. `composer why beberlei/assert` should help.
[Tests on PHP8.0 pass with ``v3.3.1` of this framework](https://github.com/web-auth/webauthn-framework/actions/runs/477484581)

**Comment by willbrowningme** [comment]
If anyone else runs into this issue it is likely that you are running `composer update` from a machine that still has php7.4 instead of php8.0. This solved it for me, I hadn't upgraded to php8.0 locally so it would not install `baberlei/assert v3.3.0`.
