### ISSUE TITLE
Safe lib used in cose-lib while not required in composer

### ISSUE THREAD

**Issue by Spomky** [web-auth/webauthn-framework#171]
See https://github.com/web-auth/cose-lib/commit/0ba9ba076238d22a1d8737e84c3caa3e16c7c876#commitcomment-46382872

**Comment by tvdijen** [comment]
Bump

**Comment by Spomky** [comment]
Hi,

This is now fixed in `v3.3.9`.
Let me know if you have any trouble with this version.
