### ISSUE TITLE
facetid from extensions for clientDataJson

### ISSUE THREAD

**Issue by ryden54** [web-auth/webauthn-framework#175]
Hello

in https://github.com/web-auth/webauthn-framework/blob/2d82c62d047cfb23fc682f840103ab0ad95f59c0/src/webauthn/src/AuthenticatorAttestationResponseValidator.php#L375
this test is always true, as the get method return an object

I think the test should be 
`case true !== $authenticationExtensionsClientOutputs->get('appid')->value()`

also on line 379, as the method expects to send a string, shouldn't we send the value of the extension?
`return $authenticationExtensionsClientInputs->get('appid')->value();`

best regards

**Comment by Spomky** [comment]
Hi,

You are right, this part does not work as expected.
It has been reviewed in the new v4.0 branch, The modification will be backported to the v3.3 branch.

**Comment by Spomky** [comment]
Hi,

This should be fixed with the tagged release `v3.3.5`.
