### ISSUE TITLE
Do not rely on SensioFrameworkExtraBundle for PSR-7 support on symfony bundle

### ISSUE THREAD

**Issue by gambry** [web-auth/webauthn-framework#179]
**Describe the bug**

With [Remove PSR-7 support](https://github.com/sensiolabs/SensioFrameworkExtraBundle/pull/710)  `sensio/framework-extra-bundle` doesn't have PSR-7 message support from version 6.0.

**To Reproduce**

1. Require `sensio/framework-extra-bundle` (either no version, or >= 6.0).
2. Add the snippet below, as per [official guide](https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-symfony-way):
```
sensio_framework_extra:
    psr_message:
        enabled: true
``` 
3. Do anything, i.e. clear the cache or open a web page.
4. See error: `Unrecognized option "psr_message" under "sensio_framework_extra". Available  options are "cache", "request", "router", "security", "templating", "view"`

**Expected behavior**
The symfony app is working as expected

**Comment by gambry** [comment]
Projects have started moving to other bundles, see https://github.com/trikoder/oauth2-bundle/issues/261 for example moving to [ajgarlag/psr-http-message-bundle](https://github.com/ajgarlag/psr-http-message-bundle).

**Comment by Spomky** [comment]
Hi @gambry,

Actually this bundle was something I wanted to integrate to the Webauthn bundle.
I am not in favor of adding a new bundle in replacement to the previous one as it may break some applications.

**Comment by gambry** [comment]
🤔 it would be nice to collaboratively work on a single replacement, but I also agree with you about adding a new bundle could break things.

I may be able to help on this. I've never played with PSR-7 myself, but I'm happy to give it a try.
How do you want to proceed? Do you want to create a bundle within this framework or add PSR-7 support as part of `web-auth/webauthn-symfony-bundle`?

**Comment by Spomky** [comment]
Hi,

I close this issue as it is now part of the new branch v4.0 (not stable yet).
Thank you for pointing this out.

**Comment by Spomky** [comment]
THis will also be backported to `v3.3`
