### ISSUE TITLE
Use Paragonie's constant time encoding library

### ISSUE THREAD

**Issue by TimWolla** [web-auth/webauthn-framework#192]
**Is your feature request related to a problem? Please describe.**

Not a problem per se. The webauthn-framework is a security library. As such I believe it should do its best to protect against any types of attacks, theoretical or not.

The current encoders and decoders are affected by cache timing leaks (or at rather: They are not defined to be immune). This attack vector should be closed by making them constant time.

**Describe the solution you'd like**

I would like to see [paragonie/constant_time_encoding](https://github.com/paragonie/constant_time_encoding) to be used for encoding and decoding (e.g. base64, base64url, Hex, …).

The existing `spomky-labs/base64url` dependency would become obsolete.

**Describe alternatives you've considered**

None. I believe the suggested library to be *the* go-to library, with Paragonie being a well-established figure in this space. With it being zero-dependency it does not come with any unrelated bloat either.

**Additional context**

n/a

**Comment by Spomky** [comment]
Hi,

I agree with you. I created the `spomky-labs/base64url` library because of the lack of base64 Url encoding in PHP (this is still the case!).
But I concur with you, this library in not safe against constant time attacks. This library from PIE is a good alternative.

**Comment by TimWolla** [comment]
@Spomky Thanks for the positive feedback. Would you like me to perform the changes? Would this be acceptable for the v3.3 target branch?

**Comment by Spomky** [comment]
Changes addressed in v4.0.
