### ISSUE TITLE
web-auth/cose-lib does not depend on web-token/jwt-core

### ISSUE THREAD

**Issue by timoschwarzer** [web-auth/webauthn-framework#193]
**Describe the bug**
The `web-auth/cose-lib` package uses `Jose\Component\Core\Util\BigInteger` from `web-token/jwt-core` but does not depend on it, resulting in class-not-found errors when not `require`ing the latter manually.

**To Reproduce**

1. In a fresh project, require `web-auth/cose-lib` and use e.g. `web-auth/cose-lib/src/Algorithm/Signature/RSA/PSSRSA.php`

Removed the rest of the template since I think it's not needed for this problem :)

**Comment by Spomky** [comment]
Hi,
This should be fixed in `v3.3.10`.
Feel free to reopen if deemed necessary.

Regards.
