### ISSUE TITLE
Missing dependency in composer.json

### ISSUE THREAD

**Issue by grambas** [web-auth/webauthn-framework#200]
**Describe the bug**
`webauthn-framework/src/cose/src/BigInteger.php` uses 2 functions from Safe namespace (`thecodingmachine/safe`):
```
use function Safe\hex2bin;
use function Safe\unpack;
```
But this package is not listed as required dependency in composer.json

**Comment by Spomky** [comment]
Hi @grambas,

This should be fixed with `v3.3.11`.
I close this issue, but feel free to reopen if necessary.

Regards.
