### ISSUE TITLE
Check if a device is already registered

### ISSUE THREAD

**Issue by Tsjippy** [web-auth/webauthn-framework#203]
**Is your feature request related to a problem? Please describe.**
First of all this is a great library thank you!

As far as I know you cannot know if a device has already been registered or not.
So I offer users who already have registered their biometrics a register button.
If they register again it will fail.

It would be good if I could query to see if they have been registered.

**Describe the solution you'd like**
A function in php or javascript which I can call to see if a device has already webauthn enabled.

**Comment by Spomky** [comment]
Hi @Tsjippy,

You cannot check if an authenticator is already registered, but you can exclude them and prevent them from being registered several times for the same user handle and RP.

This is explained [on this page](https://webauthn-doc.spomky-labs.com/the-webauthn-server/the-easy-way/register-a-new-authentication), especially the `$excludeCredentials` variable.
This feature is explained in the [Webauthn specification](https://www.w3.org/TR/webauthn-2/#dom-publickeycredentialcreationoptions-excludecredentials).

With this option, if an authenticator is already registered, it won't react on credential creation calls.

**Comment by Tsjippy** [comment]
Thanks,

yes I already made it in such a way that reregistering will fail.

But I just thought of a simple solution: if a user logged in with webauthn, it means they have it enabled for that device so I don’t have to show the register biometric button.

thanks
