### ISSUE TITLE
empty allowCredentials list is not supported on this device

### ISSUE THREAD

**Issue by e1sep0** [web-auth/webauthn-framework#204]
Hi,
I want to use usernameless authentification, after registering device, i store data in database.
When I tried log in via "Key login/FIDO2/WebAuthn" than popup is shown: "Validation failed: Use of an empty allowCredentials list is not supported on this device.". Is android not supported yet? Thank you

**Comment by Spomky** [comment]
Hi @e1sep0,

I confirm that if the `allowCredentials` is missing or empty you can't login on Android.
This works fine on other plaform such as Windows.
For usernameless authentication, the user shall be verified and a resident key shall be asked. Is it the case?

Regards.

**Comment by e1sep0** [comment]
Thank you, so this system is not suitable for my project

**Comment by Spomky** [comment]
Hi @e1sep0,

I haven't say you can't perform usernameless authentication. This is just that this feature requires specific conditions to be used.
Especially, a resident key and user verification (PIN, fingerprint...) is mandatory during the credential creation. In addition, note that if the smartphone is not genuine (jailbreak or custom Android OS), this may fail.

Regards.
