### ISSUE TITLE
Undocumented GMP extension usage in 2.1

### ISSUE THREAD

**Issue by HLeithner** [web-auth/webauthn-framework#213]
**Describe the bug**
In Version 2.1 of cose-lib in gmp_strval is used but not required by based on the composer.json. We at Joomla! uses version 2.1 in core and can't upgrade to Version 3.3 because this would likely break our SemVer policy.

Now the question is, can you backport the fix from 3.3:
```php
    private function fromBase64ToInteger(string $value): string
    {
        $data = unpack('H*', $value);
        if (false === $data) {
            throw new InvalidArgumentException('Unable to convert to an integer');
        }

        $hex = current($data);

        return BigInteger::fromBase($hex, 16)->toBase(10);
    }
```

to the 2.1 branch 

https://github.com/web-auth/cose-lib/blob/v2.1/src/Key/RsaKey.php#L186-L189

and release a new version?

**Additional context**
In case of Windows Hello (and others) it's possible that RSA keys are generated and if you don't have installed gmp the creation of the key works but the validation doesn't.

thanks

**Comment by Spomky** [comment]
Hi,

You are right. However the v2.x branch is not maintained anymore and I will not change the behavior.
In the last version, the library `brick/math` is used and it will use either GMP, BCMath or pure PHP functions depending on the platform.
With that being said, I am open for any proposal / PR to address this issue.

Regards.

**Comment by HLeithner** [comment]
Hi @Spomky

thanks for your feedback we already solved this problem in another way.
So we don't have this problem anymore.

regards
