### ISSUE TITLE
Username field is required on symfony 6

### ISSUE THREAD

**Issue by tydoo** [web-auth/webauthn-framework#218]
**Describe the bug**
On symfony 6, the `username` field is required.

**Expected behavior**
Use `email` field or `userIdentifier()` method

**Comment by Spomky** [comment]
I am not sure to clearly understand what you expect here.
Can you elaborate more on this?

**Comment by tydoo** [comment]
On Symfony 6, username field are removed for useridentifier.

So in your script you use username instead of useridentifier.

This is duplicate because we are obliged to put the email in the username field of the user.

**Comment by Spomky** [comment]
OK I know the changes with the UserInterface, but the bundle don't rely on it
