### ISSUE TITLE
Impossible to add token to a account already exist

### ISSUE THREAD

**Issue by tydoo** [web-auth/webauthn-framework#219]
How to add a token to a account already exist ?

In symfony 6, i use /register and its dosent works.

Error :
<img width="502" alt="image" src="https://user-images.githubusercontent.com/50534204/162357949-383347bb-e350-4301-9c8f-5fe1d022fb20.png">

I dont understant how to add a token to a account already exist.

Thanks to help me to understand how to take this.

My project : https://github.com/ecowan-fr/lebackoffice/tree/webauthn

**Comment by tydoo** [comment]
I found with you demo app...

But its very hard to understand because the doc is not completly updated.

Possible to update the doc ?

Thanks

**Comment by Spomky** [comment]
The `/register` paths you declare in the `security.yaml` are dedicated for new user registration.
You should use the `controller` options showed in https://webauthn-doc.spomky-labs.com/deep-into-the-framework/register-authenticators#the-symfony-way to allow users adding their own authenticators.
I have just modified this section.
