### ISSUE TITLE
HOW TO check role from user BEFORE auth

### ISSUE THREAD

**Issue by tydoo** [web-auth/webauthn-framework#229]
Hello,

How to check a role from user before auth ?

Possible to make a custom authenticator like Response Handlers ?

Thanks

**Comment by Spomky** [comment]
Hello,

To get the roles, you need the user so it needs to be authenticated.
I don't see any possibility to get roles before the user is authenticated.

What is the use case?

**Comment by tydoo** [comment]
During the authentication phase, I would like to check that the user has the "LOGIN" role which gives him the right to authenticate.

If the user does not have this role, then authentication is not performed.

**Comment by Spomky** [comment]
It looks like you need user checkers: https://symfony.com/doc/current/security/user_checkers.html

**Comment by tydoo** [comment]
Ok thanks you :)
