### ISSUE TITLE
Missing return declaration

### ISSUE THREAD

**Issue by schniko** [web-auth/webauthn-framework#240]
Hi,

unfortunately, I'm not able to make a pull request, but I found this little fix: In webauthn-symfony-bundle/src/Routing/Loader.php the function 
public function load($resource, string $type = null)
should be declared as
public function load($resource, string $type = null): mixed

The line throws a deprecation error in Symfony 6 (which this bundle is for). 

Thanks in advance 
Nicolai

**Comment by Spomky** [comment]
Hi @schniko,

You are right. I will change that in the next release.
Many thanks

**Comment by Spomky** [comment]
Hi,

This will be addressed in the version `4.1.0` to be released soon (see https://github.com/web-auth/webauthn-framework/blob/4.1.x/src/symfony/src/Routing/Loader.php).

Regards.
