### ISSUE TITLE
Add test-flag-fail-on-uncovered.sh to CI

### ISSUE THREAD

**Issue by szepeviktor** [web-auth/webauthn-framework#261]
### Description

https://github.com/web-auth/webauthn-framework/blob/5.0.x/.github/workflows/test-flag-fail-on-uncovered.sh could be replace by one CI step.

### Example

```yaml
- run: |
    vendor/bin/deptrac analyse --fail-on-uncovered --no-cache
    test "$?" -eq 1
```

**Comment by Spomky** [comment]
Many thanks:
It motivated me fixing the deptrac configuration (see #262)

I noted the test fails but it shouldn't. I guess `test "$?" -eq 1` should be `test "$?" -eq 0`.
Usually `0` means not it exited without error right?

**Comment by szepeviktor** [comment]
> I guess `test "$?" -eq 1` should be `test "$?" -eq 0`.
> Usually `0` means not it exited without error right?

If you accept only "Okay" exit status then there is no need for extra code!
```yaml
- run: |
    vendor/bin/deptrac analyse --fail-on-uncovered --no-cache
```

**Comment by Spomky** [comment]
Indeed... I guess I should read some tutorials to remind me how bash scripts works...
