### ISSUE TITLE
PublicKeyCredentialLoader->load() should support PHP array for data

### ISSUE THREAD

**Issue by davispuh** [web-auth/webauthn-framework#28]
**Is your feature request related to a problem? Please describe.**

`PublicKeyCredentialLoader->load($data)` accepts only JSON encoded string which prevents me using different serialization formats (eg. XML) or in case JSON was already decoded earlier. 

**Describe the solution you'd like**

`PublicKeyCredentialLoader->load($data)` to support already decoded PHP `array` object so it's independent of serialization format.

**Describe alternatives you've considered**
Alternative is extending `PublicKeyCredentialLoader` and reimplement it myself which isn't nice.

**Comment by davispuh** [comment]
Current `load` method would be better called as something like `loadFromJSON`

**Comment by Spomky** [comment]
Nice idea.
Done in f956f80e0285e8cb707bb2c3a0d363907ec8e9cc

Will be available in v1.1

**Comment by davispuh** [comment]
Awesome! :+1:

but `loadJson` is wrong name for that method, it should be something like `loadArray` because it has nothing to do with JSON. Once you decode JSON you have a PHP object.

for example it will look like this...
```php
$data = simplexml_load_string($xml);
$publicKeyCredentialLoader->loadJson($data); // what JSON ???
```

**Comment by Spomky** [comment]
Indeed you are right. I modified the name of the method
