### ISSUE TITLE
RS256 signature validation fails (Invalid signature)

### ISSUE THREAD

**Issue by Parsk** [web-auth/webauthn-framework#281]
Only gotten this error with Windows Hello (happens every time) that uses RS256. Yubikey that uses ES256 works perfectly. Also biometric login via an Android phone works correctly.

I've tried with both a clean laravel-webauthn install as well as with our custom implementation. Version 3.x worked as expected.

Could it be some inconsistency with base64urlsafe?

I apologize for not being able to provide more debug information.

exception: "Assert\\InvalidArgumentException"
file: "/home/test/vendor/beberlei/assert/lib/Assert/Assertion.php"
line: 2728
message: "Invalid signature."
trace: Array(61)

0: {file: '/home/test/vendor/beberlei/assert/lib/Assert/Assertion.php', line: 1812, function: 'createException', class: 'Assert\\Assertion', type: '::'}

1: {file: '/home/test/vendor/web-auth/webauthn-lib/src/AuthenticatorAssertionResponseValidator.php', line: 209, function: 'true', class: 'Assert\\Assertion', type: '::'}

2: {file: '/home/test/vendor/asbiin/laravel-webauthn/src…ervices/Webauthn/CredentialAssertionValidator.php', line: 62, function: 'check', class: 'Webauthn\\AuthenticatorAssertionResponseValidator', type: '->'}

3: {file: '/home/test/vendor/asbiin/laravel-webauthn/src/Services/Webauthn.php', line: 142, function: '__invoke', class: 'LaravelWebauthn\\Services\\Webauthn\\CredentialAssertionValidator', type: '->'}

4: {file: '/home/test/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php', line: 338, function: 'validateAssertion', class: 'LaravelWebauthn\\Services\\Webauthn', type: '::'}

5: {file: '/home/test/vendor/asbiin/laravel-webauthn/src/Actions/AttemptToAuthenticate.php', line: 92, function: '__callStatic', class: 'Illuminate\\Support\\Facades\\Facade', type: '::'}

6: {file: '/home/test/vendor/asbiin/laravel-webauthn/src/Actions/AttemptToAuthenticate.php', line: 56, function: 'attemptValidateAssertion', class: 'LaravelWebauthn\\Actions\\AttemptToAuthenticate', type: '->'}

7: {file: '/home/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php', line: 180, function: 'handle', class: 'LaravelWebauthn\\Actions\\AttemptToAuthenticate', type: '->'}

8: {file: '/home/test/vendor/asbiin/laravel-webauthn/src/Actions/EnsureLoginIsNotThrottled.php', line: 40, function: 'Illuminate\\Pipeline\\{closure}', class: 'Illuminate\\Pipeline\\Pipeline', type: '->'}

9: {file: '/home/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php', line: 180, function: 'handle', class: 'LaravelWebauthn\\Actions\\EnsureLoginIsNotThrottled', type: '->'}

10: {file: '/home/test/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php', line: 116, function: 'Illuminate\\Pipeline\\{closure}', class: 'Illuminate\\Pipeline\\Pipeline', type: '->'}

11: {file: '/home/test/vendor/asbiin/laravel-webauthn/src/Http/Controllers/AuthenticateController.php', line: 65, function: 'then', class: 'Illuminate\\Pipeline\\Pipeline', type: '->'}

12: {file: '/home/test/vendor/laravel/framework/src/Illuminate/Routing/Controller.php', line: 54, function: 'store', class: 'LaravelWebauthn\\Http\\Controllers\\AuthenticateController', type: '->'}

**Comment by Spomky** [comment]
Hi,

RSxxx algorithms are known to be very slow if GMP or BCMath extension are missing.
Can you make sure one of these extensions is installed (they are only suggested by the library)?

In addition, the v4.2.0 (to be released soon) addresses several bugs and features. Especially, the issue #242 allow a better RSA alg support for TPM (and Windows Hello).
Would you mind to test with the branch 4.2.x and tell me if it solves your issue?

Many thanks,
Regards.

**Comment by Parsk** [comment]
Hi,

Thanks for a very quick reply. php8.1-bcmath & php8.1-gmp are both installed.

I tested v4.2.0 with my own implementation and unfournanelty it did not work, I was unable to test with laravel-webauthn as it seems to have Base64UrlSafe issues when both registering and authing after version 4.0.5.

I am forced to Base64UrlSafe the response authenticatorData and clientDataJSON prior to loading them into the publicKeyCredentialLoader, could this cause inconsistency when validating the signature?

Many thanks!
Patrik

**Comment by Spomky** [comment]
> I am forced to Base64UrlSafe the response authenticatorData and clientDataJSON prior to loading them into the publicKeyCredentialLoader

Indeed, there may be a problem of encoding. The version `4.1.x` is fully compliant with the Webauthn specification and encoding rules have been fixed. Normally, this does not imply any changes on your side, but I would like to make sure of it.
Can you send me both the options (`PublicKeyCredentialRequestOptions` object) and the authenticator response (`AuthenticatorAssertionResponse ` object)? (privately if necessary)

**Comment by Parsk** [comment]
Many thanks again for taking a look, I've changed the rpID below from the real value.

(Redacted unnecessary debug data)

**Comment by Spomky** [comment]
Many thanks. Actually, I meant as json objet.

**Comment by Parsk** [comment]
Ah of course, my apologies. I seem to be unable to json_encode the AuthenticatorAssertionResponse probably due to the bytecode characters. So below is the data prior to being loaded into the credential loader.

(Redacted unnecessary debug data)

**Comment by Spomky** [comment]
Perfect.
Just one more thing: I need the public key associated to the ID `j0YQVw4ddPgNBmZIEpNi3DOwIz2fM9VqUPucYf9BGwQ`. Can you share it with me?
This public key should be available through your credential repository. The `PublicKeyCredentialSource` object can be encoded into JSON as well.

**Comment by Parsk** [comment]
Sure thing, heres the public key:
(Redacted unnecessary debug data)

**Comment by Spomky** [comment]
Excellent. Many thanks.
I isolated the bug. It was due to the `web-auth/cose-lib` dependency.
This should works now when updating this dependency to `4.0.7`.

Let me know if it is all good now.

Kind regards

**Comment by Parsk** [comment]
Aww yiss, it works! Thank you so much for taking your time to debug and for this awesome library!
