### ISSUE TITLE
Android-SafetyNet attestion created as AnonCA 

### ISSUE THREAD

**Issue by amenophis** [web-auth/webauthn-framework#299]
### Version(s) affected

4.2.0

### Description

Hello @Spomky,

Firstly, many thanks for your hard work on this library !

I'm trying to use attestation_conveyancePublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT, it works well when using a Yubikey, but not on Android nor Apple devices.

The AttestationStatement is anormaly constructed with the AttestationStatement::createAnonymizationCA method.
In AndroidSafetyNetAttestationStatementSupport::load, if I replace the construction with AttestationStatement::createBasic, it works well.

Can you tell me if the attestation is intentionnaly created with AnonCA, or if it's a bug ?

I can submit a PR to fix the issue if you confirm this is a bug.

Thanks

### How to reproduce

Configure the symfony bundle to use direct attestation conveyance, and try to register an Android / Apple device.

**Comment by Spomky** [comment]
Hi @amenophis,

For Apple devices, I am pretty sure this is the normal behaviour because the Attestation Format is `apple` and only `anonca` is supported (see https://www.w3.org/TR/webauthn-2/#sctn-apple-anonymous-attestation).
But it seems there is something wrong with Android. Both `android-safetynet` and `android-key` should return a basic attestation statement.

**Comment by Spomky** [comment]
By the way, I noted the change occurred between `4.0.x` and `4.1.x`.
This should be related to the compliance with the official FIDO Alliance testing tool. I will dig in this direction.

**Comment by Spomky** [comment]
2 minutes later... Related to https://github.com/fido-alliance/conformance-test-tools-resources/issues/687 I think

**Comment by Spomky** [comment]
Should be fixed now

**Comment by amenophis** [comment]
Thanks @Spomky,
That was really quick 😉 !

I confirm it is working with the release !
Thanks
