### ISSUE TITLE
Add support for Metadata Service

### ISSUE THREAD

**Issue by Spomky** [web-auth/webauthn-framework#31]
**Is your feature request related to a problem? Please describe.**
See https://fidoalliance.org/specs/fido-v2.0-rd-20180702/fido-metadata-service-v2.0-rd-20180702.html

This feature should implement a command or service that will perform http calls to the metadata service, retrieve and store the last dataset for all registered authenticators.
As the data from the MDS should not evolved often, the data should stay in a cache or a persistent storage to avoid unnecessary calls.

**Comment by Spomky** [comment]
Hi @moderndeveloperllc,

I am working on this feature and getting something strange with the Feitian BioPass FIDO2 authenticator metadata statement (AAGUID=`77010bd7-212a-4fc9-b236-d2ca5e9d4084`).

The answer from the metadata service is as follow:

<details>eyJhYWd1aWQiOiAiNzcwMTBiZDctMjEyYS00ZmM5LWIyMzYtZDJjYTVlOWQ0MDg0IiwgImFzc2VydGlvblNjaGVtZSI6ICJGSURPVjIiLCAiYXR0YWNobWVudEhpbnQiOiAyLCAiYXR0ZXN0YXRpb25Sb290Q2VydGlmaWNhdGVzIjogWyJNSUlCMkRDQ0FYNmdBd0lCQWdJUUdCVXJRYmREcm0yMEZabkRzWDJDQlRBS0JnZ3Foa2pPUFFRREFqQkxNUXN3Q1FZRFZRUUdFd0pWVXpFZE1Cc0dBMVVFQ2d3VVJtVnBkR2xoYmlCVVpXTm9ibTlzYjJkcFpYTXhIVEFiQmdOVkJBTU1GRVpsYVhScFlXNGdSa2xFVHlCU2IyOTBJRU5CTUNBWERURTRNRFF3TVRBd01EQXdNRm9ZRHpJd05EZ3dNek14TWpNMU9UVTVXakJMTVFzd0NRWURWUVFHRXdKVlV6RWRNQnNHQTFVRUNnd1VSbVZwZEdsaGJpQlVaV05vYm05c2IyZHBaWE14SFRBYkJnTlZCQU1NRkVabGFYUnBZVzRnUmtsRVR5QlNiMjkwSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXNGWUVFaGlKdXFxbk1nUWpTaWl2QmpWN0RHQ1RmNFhCQkgvQjd1dlpzS3hYU2hGMEw4dURJU1dVdmNFeGl4UnM2Z0Izb2xkU3Jqb3g2TDhUOTROT3pxTkNNRUF3SFFZRFZSME9CQllFRkV1OWh5WVJyUnlKendSWXZuRFNDSXhyRmlPM01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0RnWURWUjBQQVFIL0JBUURBZ0VHTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSURIU2IybWJOREFVTlh2cFBVMG9XS2VOeWUwZlEybDlEMDFBUjIrc0xaZGhBaUVBbzN3ejY4NElGTVZzQ0NSbXVKcXhINkZRUkVTTnFlenVvMUUrS2tHeFd1TT0iLCAiTUlJQjJEQ0NBWDZnQXdJQkFnSVFGWjk3d3MySkdQRW9hNU5JK3A4ejFqQUtCZ2dxaGtqT1BRUURBakJMTVFzd0NRWURWUVFHRXdKRFRqRWRNQnNHQTFVRUNnd1VSbVZwZEdsaGJpQlVaV05vYm05c2IyZHBaWE14SFRBYkJnTlZCQU1NRkVabGFYUnBZVzRnUmtsRVR5QlNiMjkwSUVOQk1DQVhEVEU0TURRd01UQXdNREF3TUZvWUR6SXdORGd3TXpNeE1qTTFPVFU1V2pCTE1Rc3dDUVlEVlFRR0V3SkRUakVkTUJzR0ExVUVDZ3dVUm1WcGRHbGhiaUJVWldOb2JtOXNiMmRwWlhNeEhUQWJCZ05WQkFNTUZFWmxhWFJwWVc0Z1JrbEVUeUJTYjI5MElFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUVuZkFLYmp2TVgxRXkxYjZrK1dRUWROVk10OUpnR1d5SjNQdk00QlNLNVhxVGZvKyswb0FqLzR0bnd5SUwwSEZCUjlTdCtrdGpxU1hEZmppWEF1cnM4Nk5DTUVBd0hRWURWUjBPQkJZRUZOR2htRTJCZjhPNWEvWUhaNzFRRXY2UVJmRlVNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdFR01Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRQzNzVDFsQmpHZUYreEtUcHpWMUtZVTJja2FoVGQ0bUxKeXpZT2hhSHY0aWdJZ0QySllrZnlINVE0QnBvOHJyb08wSXQ3b1lqRjJrZ3kvZVNaM1U5R2xhcXc9IiwgIk1JSUJmakNDQVNXZ0F3SUJBZ0lCQVRBS0JnZ3Foa2pPUFFRREFqQVhNUlV3RXdZRFZRUUREQXhHVkNCR1NVUlBJREF5TURBd0lCY05NVFl3TlRBeE1EQXdNREF3V2hnUE1qQTFNREExTURFd01EQXdNREJhTUJjeEZUQVRCZ05WQkFNTURFWlVJRVpKUkU4Z01ESXdNREJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCTkJtclJxVk94enRUSlZOMTl2dGRxY0w3dEtRZW9sMm5uTTIveVlndmtzWm5yNTBTS2JWZ0lFa3pIUVZPdTgwTFZFRTNsVmhlTzFIamdneEFsVDZvNFdqWURCZU1CMEdBMVVkRGdRV0JCUkpGV1F0MWJ2RzNqTTZYZ21WL0ljak50Ty9DekFmQmdOVkhTTUVHREFXZ0JSSkZXUXQxYnZHM2pNNlhnbVYvSWNqTnRPL0N6QU1CZ05WSFJNRUJUQURBUUgvTUE0R0ExVWREd0VCL3dRRUF3SUJCakFLQmdncWhrak9QUVFEQWdOSEFEQkVBaUF3ZlBxZ0lXSVVCK1FCQmFWR3NkSHkwczVSTXhsa3pwU1gvelN5VFptVXBRSWdCMndKNm5aUk04b1gvbkE0M1JoNlNKb3ZNMlh3Q0NILy8rTGlyQkFiQjBNPSJdLCAiYXR0ZXN0YXRpb25UeXBlcyI6IFsxNTg3OV0sICJhdXRoZW50aWNhdGlvbkFsZ29yaXRobSI6IDEsICJhdXRoZW50aWNhdG9yVmVyc2lvbiI6IDEsICJjcnlwdG9TdHJlbmd0aCI6IDEyOCwgImRlc2NyaXB0aW9uIjogIkZlaXRpYW4gQmlvUGFzcyBGSURPMiBBdXRoZW50aWNhdG9yIiwgImljb24iOiAiZGF0YTppbWFnZS9wbmc7YmFzZTY0LGlWQk9SdzBLR2dvQUFBQU5TVWhFVWdBQUFGQUFBQUFVQ0FNQUFBQXRCa3JsQUFBQUdYUkZXSFJUYjJaMGQyRnlaUUJCWkc5aVpTQkpiV0ZuWlZKbFlXUjVjY2xsUEFBQUJIWnBWRmgwV0UxTU9tTnZiUzVoWkc5aVpTNTRiWEFBQUFBQUFEdy9lSEJoWTJ0bGRDQmlaV2RwYmowaTc3dS9JaUJwWkQwaVZ6Vk5NRTF3UTJWb2FVaDZjbVZUZWs1VVkzcHJZemxrSWo4K0lEeDRPbmh0Y0cxbGRHRWdlRzFzYm5NNmVEMGlZV1J2WW1VNmJuTTZiV1YwWVM4aUlIZzZlRzF3ZEdzOUlrRmtiMkpsSUZoTlVDQkRiM0psSURVdU5pMWpNREUwSURjNUxqRTFOamM1Tnl3Z01qQXhOQzh3T0M4eU1DMHdPVG8xTXpvd01pQWdJQ0FnSUNBZ0lqNGdQSEprWmpwU1JFWWdlRzFzYm5NNmNtUm1QU0pvZEhSd09pOHZkM2QzTG5jekxtOXlaeTh4T1RrNUx6QXlMekl5TFhKa1ppMXplVzUwWVhndGJuTWpJajRnUEhKa1pqcEVaWE5qY21sd2RHbHZiaUJ5WkdZNllXSnZkWFE5SWlJZ2VHMXNibk02ZUcxd1BTSm9kSFJ3T2k4dmJuTXVZV1J2WW1VdVkyOXRMM2hoY0M4eExqQXZJaUI0Yld4dWN6cGtZejBpYUhSMGNEb3ZMM0IxY213dWIzSm5MMlJqTDJWc1pXMWxiblJ6THpFdU1TOGlJSGh0Ykc1ek9uQm9iM1J2YzJodmNEMGlhSFIwY0RvdkwyNXpMbUZrYjJKbExtTnZiUzl3YUc5MGIzTm9iM0F2TVM0d0x5SWdlRzFzYm5NNmVHMXdUVTA5SW1oMGRIQTZMeTl1Y3k1aFpHOWlaUzVqYjIwdmVHRndMekV1TUM5dGJTOGlJSGh0Ykc1ek9uTjBVbVZtUFNKb2RIUndPaTh2Ym5NdVlXUnZZbVV1WTI5dEwzaGhjQzh4TGpBdmMxUjVjR1V2VW1WemIzVnlZMlZTWldZaklpQjRiWEE2UTNKbFlYUnZjbFJ2YjJ3OUlrRmtiMkpsSUZCb2IzUnZjMmh2Y0NCRFF5QXlNREUwSUNoTllXTnBiblJ2YzJncElpQjRiWEE2UTNKbFlYUmxSR0YwWlQwaU1qQXhOaTB4TWkwek1GUXhORG96TXpvd09Dc3dPRG93TUNJZ2VHMXdPazF2WkdsbWVVUmhkR1U5SWpJd01UWXRNVEl0TXpCVU1EYzZNekU2TlRrck1EZzZNREFpSUhodGNEcE5aWFJoWkdGMFlVUmhkR1U5SWpJd01UWXRNVEl0TXpCVU1EYzZNekU2TlRrck1EZzZNREFpSUdSak9tWnZjbTFoZEQwaWFXMWhaMlV2Y0c1bklpQndhRzkwYjNOb2IzQTZTR2x6ZEc5eWVUMGlNakF4TmkweE1pMHpNRlF4TlRvek1Eb3lOeXN3T0Rvd01DWWplRGs3NXBhSDVMdTJJT2FjcXVhZ2grbWltQzB4SU9XM3N1YUprK1c4Z0NZamVFRTdJaUI0YlhCTlRUcEpibk4wWVc1alpVbEVQU0o0YlhBdWFXbGtPakpGTnpGQ1JrWkRRelkzUmpFeFJUWTVOemhFUVRsRFFrSTJORFl6Umprd0lpQjRiWEJOVFRwRWIyTjFiV1Z1ZEVsRVBTSjRiWEF1Wkdsa09qSkZOekZDUmtaRVF6WTNSakV4UlRZNU56aEVRVGxEUWtJMk5EWXpSamt3SWo0Z1BIaHRjRTFOT2tSbGNtbDJaV1JHY205dElITjBVbVZtT21sdWMzUmhibU5sU1VROUluaHRjQzVwYVdRNk1rVTNNVUpHUmtGRE5qZEdNVEZGTmprM09FUkJPVU5DUWpZME5qTkdPVEFpSUhOMFVtVm1PbVJ2WTNWdFpXNTBTVVE5SW5odGNDNWthV1E2TWtVM01VSkdSa0pETmpkR01URkZOamszT0VSQk9VTkNRalkwTmpOR09UQWlMejRnUEM5eVpHWTZSR1Z6WTNKcGNIUnBiMjQrSUR3dmNtUm1PbEpFUmo0Z1BDOTRPbmh0Y0cxbGRHRStJRHcvZUhCaFkydGxkQ0JsYm1ROUluSWlQejQ3N0pYRkFBQUFZRkJNVkVYLy8vOEVWcUlYWmF2RzJPb3FjTEcyek9Pa3d0MEJTSnRxbGNYVjR1K2F1dGxXaGJ6azdQVUFNWTlIY3JLanROYnE4ZmVBbDhhQm9zeno5dnBkanNHR3F0RjNuOHVUc05TWnBjNkpzTlQ1K3YweFlLbnU4UGZmNS9MNDhmZy9mcmljekpnWUFBQURBRWxFUVZSNDJrUlVDWmJESUFqRlhaT1kxVGF0TmMzOWJ6a3NTWWMzcjRNRTRmTUJBYUQ2emw4eS85VE9nZXQ4ZDVqZk43OGJ3TS9kRENScFI1MjF6WGZvakhKMDVJSXloQkFVU1ZBT05kR3pCWXQyZjdLRnJma0phQWtIaDlGWmhjRFhIUmtUS285TUxpaEdhYXZJbW5WM3F5RVgwRXByZ3ovNER3VUQ3a0NIUm5kOFFGTjQzR280VVZtRERnemE0dzI3b2l6ZEEyK2NLK3V1VXBqam8yK3h3Yy80Mlc1MHg1TEdZZURCc1IwSFZJeDV4OGlGNjBDYmxiVEVFa0ZyMjdiTkRCVVZTcTFPS1ZQYkU2MmIzRUg4RnFCZzVPT09FdWMydDhaSmlxTU91R3ArY0tqZzd3VkdjZW96cU40cHhnVlBRa2pGWWdiVkpLRFVoRENqWXJhd1A1cTRFVGdDOWZJTVJIdGl0cFFjQ3ZKT0VMY2JNc1FnbmNpUmtsanB5UWp2RzQ0anFCVUVURmlCaTFQRUl5ZWtPenNXK1R5NWNMSG9zNVIrZE1TMUx0U1N4ZjNnUUhjelIyQ0k0Z01OcFc0SVJBMVFNYTZ0SjQrQzZ1SHVHRThtTkRJeUZxZy9PUC9NTVV1ZVM2SXE4UzkwZEFlQkpTRXkvcUtrSytCTnd6OGNZWTRqYjVKNnU0aVdDSTJCMVo1NkxXNWtFYzRoa2RNcHN2VUM1NTg1U1gwUXViY2dOcXlmZ0RGRWNUdCs0MC8wUzVOeDB3YUN3M09La2NPYkE1SW4wQVlwMDFwamp3Mm42MjZVRGp0SHdhMjhpSHVUS3F0cnYrcmVXNDFOWjZpR2xyN3V1TEpDZmtGdGN0Y0cwNHNnbTFlTlMrWmFEbnBhVEVyR295WDVKSzJpTXo4eHMwbk93V0djUERONDlxYUNkNGJ6Sm96RFptL2FCSytFb3pMdytYaE5CaVl3SGYwc2lPdTFYUGtHL3pLd3ZxWUtjZlN3REVjSC9vVWUwN2VzL1dROHJJeWcyRE9Yajh0amtaZHVEQi9iOGh6RGxsTU1PQ1M1QkVuZDUzNGY4dGkzVVpjNGtNczN4THlhZk1Tc0poZEc4WFBxak5rNXRBZ08yNWZlS0NoblZkRGovSjBGTWtPc1UveE1CdjB3RmhZZUVHZlZIMTNmdURVMHlERkxhNGZjN1JuV0hCZnVURlYydEVtTndhZGM3YWMzVVkyamZCbDdIVDM2ZmUzNGlRTzVtTkNGRkJXMDdLalBncWhPTFUwMXZaOFB1ZVoySkNsRlpOOGprVXM2OXVrYTllUHA2K0VmTDRBRjUrTnl3U2Jpckh0Y0I4TWwvZ2t3QUVqa0s2NEtqSFBlQUFBQUFFbEZUa1N1UW1DQyIsICJpc1NlY29uZEZhY3Rvck9ubHkiOiBmYWxzZSwgImtleVByb3RlY3Rpb24iOiAxMCwgImxlZ2FsSGVhZGVyIjogIk1ldGFkYXRhIExlZ2FsIEhlYWRlcjogVmVyc2lvbiAxLjAwLlx1MzAwMERhdGU6IE1heSAyMSwgMjAxOC4gIFRvIGFjY2VzcywgdmlldyBhbmQgdXNlIGFueSBNZXRhZGF0YSBTdGF0ZW1lbnRzIG9yIHRoZSBUT0MgZmlsZSAoXHUyMDFjTUVUQURBVEFcdTIwMWQpIGZyb20gdGhlIE1EUywgWW91IG11c3QgYmUgYm91bmQgYnkgdGhlIGxhdGVzdCBGSURPIEFsbGlhbmNlIE1ldGFkYXRhIFVzYWdlIFRlcm1zIHRoYXQgY2FuIGJlIGZvdW5kIGF0IGh0dHA6Ly9tZHMyLmZpZG9hbGxpYW5jZS5vcmcvIC4gSWYgeW91IGFscmVhZHkgaGF2ZSBhIHZhbGlkIHRva2VuLCBhY2Nlc3MgdGhlIGFib3ZlIFVSTCBhdHRhY2hpbmcgeW91ciB0b2tlbiBzdWNoIGFzIGh0dHA6Ly9tZHMyLmZpZG9hbGxpYW5jZS5vcmc_dG9rZW49WU9VUi1WQUxJRC1UT0tFTi4gIElmIFlvdSBoYXZlIG5vdCBlbnRlcmVkIGludG8gdGhlIGFncmVlbWVudCwgcGxlYXNlIHZpc2l0IHRoZSByZWdpc3RyYXRpb24gc2l0ZSBmb3VuZCBhdCBodHRwOi8vZmlkb2FsbGlhbmNlLm9yZy9NRFMvIGFuZCBlbnRlciBpbnRvIHRoZSBhZ3JlZW1lbnQgYW5kIG9idGFpbiBhIHZhbGlkIHRva2VuLiAgWW91IG11c3Qgbm90IHJlZGlzdHJpYnV0ZSB0aGlzIGZpbGUgdG8gYW55IHRoaXJkIHBhcnR5LiBSZW1vdmFsIG9mIHRoaXMgTGVnYWwgSGVhZGVyIG9yIG1vZGlmeWluZyBhbnkgcGFydCBvZiB0aGlzIGZpbGUgcmVuZGVycyB0aGlzIGZpbGUgaW52YWxpZC4gIFRoZSBpbnRlZ3JpdHkgb2YgdGhpcyBmaWxlIGFzIG9yaWdpbmFsbHkgcHJvdmlkZWQgZnJvbSB0aGUgTURTIGlzIHZhbGlkYXRlZCBieSB0aGUgaGFzaCB2YWx1ZSBvZiB0aGlzIGZpbGUgdGhhdCBpcyByZWNvcmRlZCBpbiB0aGUgTURTLiBUaGUgdXNlIG9mIGludmFsaWQgZmlsZXMgaXMgc3RyaWN0bHkgcHJvaGliaXRlZC4gSWYgdGhlIHZlcnNpb24gbnVtYmVyIGZvciB0aGUgTGVnYWwgSGVhZGVyIGlzIHVwZGF0ZWQgZnJvbSBWZXJzaW9uIDEuMDAsIHRoZSBNRVRBREFUQSBiZWxvdyBtYXkgYWxzbyBiZSB1cGRhdGVkIG9yIG1heSBub3QgYmUgYXZhaWxhYmxlLiBQbGVhc2UgdXNlIHRoZSBNRVRBREFUQSB3aXRoIHRoZSBMZWdhbCBIZWFkZXIgd2l0aCB0aGUgbGF0ZXN0IHZlcnNpb24gbnVtYmVyLiAgRGF0ZWQ6IDIwMTgtMDUtMjEgVmVyc2lvbiBMSC0xLjAwIiwgIm1hdGNoZXJQcm90ZWN0aW9uIjogNCwgIm9wZXJhdGluZ0VudiI6ICJTZWN1cmUgRWxlbWVudCAoU0UpIiwgInByb3RvY29sRmFtaWx5IjogImZpZG8yIiwgInB1YmxpY0tleUFsZ0FuZEVuY29kaW5nIjogMjYwLCAidGNEaXNwbGF5IjogMCwgInVwdiI6IFt7Im1ham9yIjogMSwgIm1pbm9yIjogMH1dLCAidXNlclZlcmlmaWNhdGlvbkRldGFpbHMiOiBbW3sidXNlclZlcmlmaWNhdGlvbiI6IDJ9XSwgW3sidXNlclZlcmlmaWNhdGlvbiI6IDF9XV19
</details>

When base64 decoded, this statement looks like a json object, but contains invalid characters (binary ones).

Have you (or anybody receiving this issue) have access to the metadata service? 
If yes, can you corfirm the data is invalid?

Thanks in advance.

**Comment by moderndeveloperllc** [comment]
There does seem to be something wrong with the entry for that authenticator. I can do the API call for `ee041bce-25e5-4cdb-8f86-897fd6418464` (Feitian ePass FIDO2-NFC Authenticator) and the data parses properly.

I'm not planning on using the MDS mainly because it is very incomplete. The biggest key maker, [Yubico](https://www.yubico.com/solutions/fido2/), isn't in the TOC, nor is [Solo](https://shop.solokeys.com/). Having it in your framework might be a nice, "It may be useful in the future" feature though.

Right now, I'm just parsing the certificate and storing the CN as a user-readable name the user can change later.

(in a class that extends `PublicKeyCredentialSource`)
```
if ($this->trustPath instanceof CertificateTrustPath) {
    $certInfo = openssl_x509_parse($this->trustPath->getCertificates()[0]);
    $this->setFriendlyName($certInfo['subject']['CN']);
} else {
    $this->setFriendlyName(base64_encode($this->aaguid) . ' (Key AAGUID)');
}
```

**Comment by Spomky** [comment]
Thank you for the quick reply and confirmation. Il will send a feedback message to the FIDO Alliance.
I agree with you, the data does not include all the authenticators and this feature is not really exciting at the moment.
The data is also outdated (next update is set to `2019-04-03`).

In the absence of statement, your approach is interesting.

I’ve just pushed some new lines of code in dedicated branch and brand new PR #50.
I planned to introduce this feature will be part of a dedicated library with v1.2, but I think I’ll wait a bit.

**Comment by Spomky** [comment]
Closing for now.
Ongoing #50
