### ISSUE TITLE
psr/log flexibility

### ISSUE THREAD

**Issue by iganev** [web-auth/webauthn-framework#326]
### Description

Would it be possible to make psr/log more flexible in terms of versioning requirements? 

Huge portion of the PHP ecosystem still relies on psr/log ^1.1.0, while webauthn requires psr/log ^3.

**Comment by Spomky** [comment]
Hi,

No pb for me.
Will be intergrated from v4.2.x. See ##328

**Comment by Spomky** [comment]
Done. Will be released soon
