### ISSUE TITLE
Make PublicKeyCredentialLoader::load not emit \JsonException

### ISSUE THREAD

**Issue by TimWolla** [web-auth/webauthn-framework#346]
`PublicKeyCredentialLoader::load()` throws the original `JsonException`. It might be useful to create a dedicated library-specific Exception that wraps the JsonException using `$previous`.

_Originally posted by @TimWolla in https://github.com/web-auth/webauthn-framework/issues/295#issuecomment-1277696659_
      
-----------------------

`InvalidDataException` that is already used in `loadArray()` might be appropriate.

**Comment by TimWolla** [comment]
Not stale.

**Comment by Spomky** [comment]
Addressed in #365.
Feel free to re-open if the expected behaviour is still incorrect.

Regards.
