### ISSUE TITLE
AuthenticatorAttestationResponseValidator::create() a non-null TokenBindingHandler object

### ISSUE THREAD

**Issue by emmanuel-deloget** [web-auth/webauthn-framework#347]
### Version(s) affected

4.4.2

### Description

This is really a two step issue : 

* AuthenticatorAttestationResponseValidator::__construct() triggers a deprecation warning if we give it a non-null TokenBindingHandler instance ; 
* but the ::create() method of the same object requires the TokenBindingHandler to be non-null

The same is also true for AuthenticatorAssertionResponseValidator and maybe some other classes (I haven't checked).

### How to reproduce

call AuthenticatorAttestationResponseValidator::create() with a null $tokenBindingHandler parameter. 

### Possible Solution

Mark $tokenBindingHandler in ::create() methods as nullable (?TokenBindingHandler).

**Comment by Spomky** [comment]
Addressed by #349
