### ISSUE TITLE
trigger_deprecation() is not defined

### ISSUE THREAD

**Issue by emmanuel-deloget** [web-auth/webauthn-framework#348]
### Version(s) affected

4.4.2

### Description

Passing a non-null $tokenBindingHandler parameter to the constructor of (for example) AuthenticatorAssertionResponseValidator triggers a deprecation warning through the use of **trigger_deprecation()**.Unfortunately, this method is not defined (and thus an PHP Error is generated instead of a deprecation warning).

It seems the project lacks a dependency on symfony/deprecation-contracts.

### How to reproduce

Create an AuthenticatorAssertionResponseValidator object with a non-null $tokenBindingHandler.

### Possible Solution

Either 
* add a dependency on symfony/deprecation-contracts
* or implement a private version of trigger_deprecation()
* use trigger_error(..., E_USER_DEPRECATED) instead of symfony's trigger_deprecation()

### Additional Context

We only depend on the web-auth/webauthn-lib package but it seems composer.json on web-auth/webauthn-framework lacks the dependency on symfony/deprecation-contract as well.

**Comment by Spomky** [comment]
Hi,

Many thanks for pointing this out.
Adding `symfony/deprecation-contracts` looks good to me.
I will prepare a PR for that and tag it ASAP
