### ISSUE TITLE
[DOC] Relying, not Relaying

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-auth/webauthn-framework#35]
Just a small typo in your docs. The specification talks about a [Relying Party](https://www.w3.org/TR/webauthn/#webauthn-relying-party), but you have Rel**a**ying Party. It makes a difference in understanding the workflow. Google Translate seems to have an issue with these words. C'est la différence entre "la partie se fiant" (relying party) et "la partie relais" (relaying party).

And yes, I seem to be using quite a few of your projects!

**Comment by Spomky** [comment]
Thank you for pointing this out.
I modified some pages accordingly.
I let this issue opened until every pages/code lines are fixed.
French translations for relying party could be "entité de confiance" and for relaying party we could simply use "relais". I'm not sure "relaying party" is correct anyway, "third party" (tierce party/service intermédiaire) would be more appropriate.

Thank you for the trust you have in these projects. 
I am really happy to receive all your issues that helps me a lot to improve all of them.

Have you tried [the demo](https://webauthn.spomky-labs.com/)?
It is based on the next v1.1 and should work on practically every FIDO2 compatible devices.

**Comment by moderndeveloperllc** [comment]
No a problem. It's been almost 30 years since I studied French, so I was just going off [what I found online](https://context.reverso.net/translation/english-french/the+relying+party). I tried the demo and it's really nice to see the code working. I may steal your security key image, it's quite nice!

From what I've seen, you write good code. More importantly, you seem to care about these projects and react to issues quickly. I'm using v1.1 to develop with as it seems minimally stable. I'll wait to comment further on the docs till you release the version as I'm sure you will be going through them once all your changes are made.

**Comment by Spomky** [comment]
Closing as resolved.
Thank you :+1:

**Comment by aaronpk** [comment]
It looks like this is still called "relaying" in the docs.

![image](https://user-images.githubusercontent.com/113001/138119811-12090b75-f005-446d-948d-2a37a7905c08.png)

I wasn't able to find the source repository for the doc site otherwise I would have sent a PR to fix it myself.

**Comment by Spomky** [comment]
Oh! Looks like I wrote the doc while sleeping 😴.
Let me take care of this.

**Comment by Spomky** [comment]
Hi @aaronpk,

The doc is now up to date.
The source repository is in https://github.com/web-auth/doc
Feel free to ask if anything is unclear, I will do my best to help you.

Regards

**Comment by aaronpk** [comment]
Excellent thanks!

Sorry I missed finding it in that repo before, I didn't realize it was all behind tags!
