### ISSUE TITLE
Question: base64 encode/decode of $id in PublicKeyCredentialUserEntity

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-auth/webauthn-framework#36]
I noticed a curious quirk that `PublicKeyCredentialUserEntity` will base64 encode/decode `$id` on JSON serialization. Since the roundtrip works, nothing it broken per se, but I was curious as to the decision to do any encoding that parameter.

User entities are most likely coming from a datastore of some sort, so having a non JSON-safe $id would be rather rare would it not?

**Comment by Spomky** [comment]
In the specification, the user ID corresponds to the [user handle](https://www.w3.org/TR/webauthn/#user-handle) which is defined as follow:

>A user handle is an opaque byte sequence with a maximum size of 64 bytes. User handles are not meant to be displayed to users. The user handle SHOULD NOT contain personally identifying information about the user, such as a username or e-mail address; see §14.9 User Handle Contents for details.

As it is a byte string, we could imagine implementations where non-printable characters are used.

From my point of view the user handle should not be the ID used as database index to avoid disclosure of sensitive information (this is not what I do in the deno by the way...) and potential security issue. 

Anyway I agree with you we will rarely see such ID. 

Just for fun, I will check if it works fine with that framework.
