### ISSUE TITLE
Can't use YubicoKey because userHandle is always null on authentication

### ISSUE THREAD

**Issue by rochamarcelo** [web-auth/webauthn-framework#362]
### Version(s) affected

4.4.1

### Description

When using Yubico Key for authentication the userHandle is empty in the response from the browser but the method `AuthenticatorAssertionResponseValidator::check` does not allow empty value for $responseUserHandle.

Reading the doc https://www.w3.org/TR/webauthn/#conforming-authenticators-u2f I found this 
``` 
2.2.1. Backwards Compatibility with FIDO U2F
[Authenticators](https://www.w3.org/TR/webauthn/#authenticator) that only support the [§ 8.6 FIDO U2F Attestation Statement Format](https://www.w3.org/TR/webauthn/#sctn-fido-u2f-attestation) have no mechanism to store a [user handle](https://www.w3.org/TR/webauthn/#user-handle), so the returned [userHandle](https://www.w3.org/TR/webauthn/#dom-authenticatorassertionresponse-userhandle) will always be null.
``` 

The error happens at https://github.com/web-auth/webauthn-framework/blob/4.5.x/src/webauthn/src/AuthenticatorAssertionResponseValidator.php#L126 

Did I missed something?

### How to reproduce

Try to authenticate with YubicoKey.

You can check the source code used at https://github.com/rochamarcelo/users/blob/cake5/src/Webauthn/AuthenticateAdapter.php#L63

```

if ($authenticatorAssertionResponse instanceof AuthenticatorAssertionResponse) {
            $authenticatorAssertionResponseValidator = new AuthenticatorAssertionResponseValidator(
                $this->repository,
                null,
                $this->createExtensionOutputCheckerHandler(),
                $this->getAlgorithmManager()
            );

            return $authenticatorAssertionResponseValidator->check(
                $publicKeyCredential->getRawId(),
                $authenticatorAssertionResponse,
                $options,
                $this->request,
                null
            );
        }

```

**Comment by Spomky** [comment]
Hi,

There are two use cases when authenticating a user:
1. Either you know the username
2. Or you don't know it

For the latter, it requires specific authenticators and user verification (done using a PIN code, fingerprint...).
The case you are using is the first one. The username is used for generating the Authenticator Options and for checking the Authenticator Assertion.
In the [`AuthenticateAdapter::verifyResponse`](https://github.com/rochamarcelo/users/blob/cake5/src/Webauthn/AuthenticateAdapter.php#L55), you must retreive the user entity and pass it as the fifth argument of the `check` method.
I am not sure how to proceed with your application, but maybe calling ` $userEntity = $this->getUserEntity();` in `verifyResponse` (as done at [AuthenticateAdapter.php#L30](https://github.com/rochamarcelo/users/blob/cake5/src/Webauthn/AuthenticateAdapter.php#L30)) or using the session should work fine.

**Comment by rochamarcelo** [comment]
Thank you @Spomky for the help. I was able to integrate the library.

By the way the code is for a CakePHP plugin that I'm migrating from 3.x to 4.x. 

While working on this I have sent a few pull request to the doc repository.

https://github.com/web-auth/doc/pulls

**Comment by Spomky** [comment]
Excellent!

Many thanks for your contributions.
I will take time to align the documentation with the latest changes and especially the coming v4.5

**Comment by Spomky** [comment]
Hi @rochamarcelo,

Thank you for supporting me 🎉.
I would like to tweet about it and the work done for CakePHP. Do you have a Twitter/Mastodon account to mention?

Many thanks.
Regards.

**Comment by rochamarcelo** [comment]
I'm happy to support, this library has been very helpful. My twitter is [@mrcodex](https://twitter.com/mrcodex)
