### ISSUE TITLE
fgrosse/phpasn1 is abandonned

### ISSUE THREAD

**Issue by tydoo** [web-auth/webauthn-framework#364]
### Version(s) affected

4.4.1

### Description

https://packagist.org/packages/fgrosse/phpasn1

is abandonned

fgrosse/phpasn1 is dependency of web-auth/webauthn-lib

### How to reproduce

On https://packagist.org/packages/fgrosse/phpasn1

`This package is abandoned and no longer maintained. No replacement package was suggested.`

**Comment by Spomky** [comment]
Hi,

This is already addressed in [the 4.5.x branch](https://github.com/web-auth/webauthn-framework/blob/4.5.x/composer.json#L36-L63) that will be released soon.

**Comment by Spomky** [comment]
Closing as 4.5.0 is now released
