### ISSUE TITLE
Misleading deprecation message when passing a PSR-7 ServerRequestInterface

### ISSUE THREAD

**Issue by TimWolla** [web-auth/webauthn-framework#369]
### Description

> Since web-auth/webauthn-lib 4.5.0: The class "Webauthn\AuthenticatorAttestationResponseValidator" is deprecated since 4.5.0 and will be removed in 5.0.0. Please inject the host as a string instead.

Should this read:

> Since web-auth/webauthn-lib 4.5.0: Passing a ServerRequestInterface to the class "Webauthn\AuthenticatorAttestationResponseValidator" is deprecated since 4.5.0 and will be removed in 5.0.0. Please inject the host as a string instead.

?

**Comment by Spomky** [comment]
Yes. This is correct. I will change that ASAP

**Comment by Spomky** [comment]
~More specifically, it is only for the `check` method~
