### ISSUE TITLE
Usernames Enumeration

### ISSUE THREAD

**Issue by Spomky** [web-auth/webauthn-framework#37]
**Is your feature request related to a problem? Please describe.**
At the moment, the firewall triggers an error when a username does not exist. This could be used by an attacker to find usernames and associated key descriptors. 

**Describe the solution you'd like**
No error should be triggered if the username does not exist. 
A list of fake key descriptors should be generated. This list should be always the same for a given username.

**Comment by Spomky** [comment]
Partially fixed in Json Firewall (https://github.com/web-auth/webauthn-framework/commit/a9cd2f4ef67fca8b458c29d5e5b9bb427e424334)

**Comment by Spomky** [comment]
Recommendations added to the documentation

**Comment by AlexH269** [comment]
Is this still relevant with the current version? Looks like by default it is still possible to use this mechanism to determine which users do and do not exist.

**Comment by Spomky** [comment]
Yes it is and there is no efficient way to prevent it.
The Fake User Entity Support mentionned above has been removed in the last major release as this feature creates lot of issues.
Best is to let users to choose a username without any constraint and recommend them to avoid personal data e.g. real name or e-mail address.

**Comment by AlexH269** [comment]
OK, in my use case the username is pre determined anyway. Thanks for the quick response.
