### ISSUE TITLE
PublicKeyCredentialSourceRepository shouldn't be required

### ISSUE THREAD

**Issue by tomsommer** [web-auth/webauthn-framework#375]
The source makes no use of `findAllForUserEntity` in `PublicKeyCredentialSourceRepository` and only uses `saveCredentialSource` during `AuthenticatorAssertionResponseValidator` (why is this?)
It makes no sense to have `findAllForUserEntity` and possibly `saveCredentialSource`  in the `PublicKeyCredentialSourceRepository` interface.

All in all, it makes little sense for this library to require a `SourceRepository` at all, since only `findOneByCredentialId` is really used, and this data could be provided as an argument to the function using it instead

**Comment by Spomky** [comment]
Hello,

The method `findAllForUserEntity` is used for 2 use cases:

* When a user adds an additional authenticator, it is used for excluding already registered authenticators,
* When a user logs in, they are used as hints by the client.

The method `saveCredentialSource` is called by `AuthenticatorAssertionResponseValidator` because the `counter` evolves each time the authenticator is used. This parameter is necessary to prevent replay attacks.

**Comment by lukewarlow** [comment]
I agree that this repository doesn't seem a good fit for this library. In my opinion leaving as much of the architecture decisions up to the consumer of the library is best. Especially now that in v4 the library doesn't actually provide the "Server" class that pulls it all together.

`findOneByCredentialId` uses a credentialId parameter that you as the consumer pass through to the library. As said above this library could just take through the credential itself as a parameter.

`findAllForUserEntity` is never called within the library itself.

`saveCredentialSource` doesn't really need to be in the library on the basis that the object it's saving get returned from the check function that it's called in, so again the saving could just be left to the consumer of the library.

**Comment by Spomky** [comment]
> findOneByCredentialId uses a credentialId parameter that you as the consumer pass through to the library. As said above this library could just take through the credential itself as a parameter.

Correct

> findAllForUserEntity is never called within the library itself.

Correct

> saveCredentialSource doesn't really need to be in the library on the basis that the object it's saving get returned from the check function that it's called in, so again the saving could just be left to the consumer of the library.

Makes sense to me. This method was added to make sure the counter value is really up to date.
I will take time to address these points.

**Comment by Spomky** [comment]
Hi @tomsommer, @lukewarlow,

I started working on this issue and opened PR #384 to fix it.
It's not an easy task to deprecate it without breaking things, but it seems to be working fine so far.
I tested it with the [the demo app](https://github.com/web-auth/symfony-demo) and it works fine without any use of deprecated, but maybe you could test it on your own project before I merge it.

Kind regards.

**Comment by tomsommer** [comment]
Thank you for this @Spomky 🙏
