### ISSUE TITLE
AuthenticatorSelectionCriteria::setResidentKey fails

### ISSUE THREAD

**Issue by henkpb** [web-auth/webauthn-framework#376]
### Version(s) affected

4.5.0

### Description

After upgrading from version 4.0.5 to 4.5.0, I ran into an issue when setting criteria for autenticator selection.
Using a similar code fragment as documented in [https://webauthn-doc.spomky-labs.com/pure-php/advanced-behaviours/authenticator-selection-criteria#resident-key](url), the following fatal error occurs: "Uncaught TypeError: Webauthn\AuthenticatorSelectionCriteria::setResidentKey(): Argument #1 ($residentKey) must be of type string, null given"

### How to reproduce

`$authenticatorSelectionCriteria = AuthenticatorSelectionCriteria::create()`
`  ->setUserVerification(AuthenticatorSelectionCriteria::USER_VERIFICATION_REQUIREMENT_DISCOURAGED)`
`  ->setResidentKey(AuthenticatorSelectionCriteria::RESIDENT_KEY_REQUIREMENT_NO_PREFERENCE)`
`  ->setAuthenticatorAttachment(AuthenticatorSelectionCriteria::AUTHENTICATOR_ATTACHMENT_PLATFORM)`

### Possible Solution

In AuthenticatorSelectionCriteria.php, function setResidentKey is declared as:
`public function setResidentKey(string $residentKey): self`

And:
`final public const RESIDENT_KEY_REQUIREMENT_NO_PREFERENCE = null;`

Unfortunately `setResidentKey()` does not like null values.

How should we handle this properly?

**Comment by Spomky** [comment]
Hi,

Thank you for reporting this issue. This should be fixed by `4.5.1`.

Regards.
