### ISSUE TITLE
E-mail addresses as usernames

### ISSUE THREAD

**Issue by Spomky** [web-auth/webauthn-framework#38]
**Is your feature request related to a problem? Please describe.**
As explained in the specification, the e-mail addresses should not be used as usernames. 

**Describe the solution you'd like**
A a section in the doc about all security means that can be implemented.
Should be linked to #37

**Comment by moderndeveloperllc** [comment]
@Spomky I personally have no issue with this for `PublicKeyCredentialUserEntity::$id` (I use UUIDs), but the [spec only indicates](https://www.w3.org/TR/webauthn/#sctn-username-enumeration) "may" restrict (as a best-practices implementation). Are you going to have this as an optional flag when creating a `PublicKeyCredentialUserEntity`?

**Comment by Spomky** [comment]
Hi @moderndeveloperllc 

This is related to the `PublicKeyCredentialUserEntity::$name` parameter (inherited from `PublicKeyCredentialEntity`) and not the `$id` one.
You are right to say that this is not a requirement, but just an advice and there is no obligation to strongly restrict e-mail addesses as usernames.

I will change that into a section in the doc about security topics.

**Comment by moderndeveloperllc** [comment]
Actually, it does refer [to the user.id](https://www.w3.org/TR/webauthn/#sctn-user-handle-privacy).
```
... SHOULD NOT include personally identifying information,
e.g., e-mail addresses or usernames, in the user handle.
```
[User handle](https://www.w3.org/TR/webauthn/#user-handle) is defined as: 
```
The user handle is specified by a Relying Party, as the value of user.id,
and used to map a specific public key credential to a specific user account
with the Relying Party. Authenticators in turn map RP IDs and user handle
pairs to public key credential sources.
```
User name is described as being [able to be an email address:](https://www.w3.org/TR/webauthn/#dictdef-publickeycredentialentity)
```
When inherited by PublicKeyCredentialUserEntity, it is a human-palatable identifier
for a user account. It is intended only for display, i.e., aiding the user in determining
the difference between user accounts with similar displayNames.
For example, "alexm", "alex.p.mueller@example.com" or "+14255551234".
```

**Comment by Spomky** [comment]
:+1: 

`user.id` = user handle: UUID or any random bytes string (up to 64 bytes). Defined by the rp i.e. the server in this case.
`user.name`: username made of printable characters (works fine UTF8 chars, emojis...). Usually defined by the user.

Both values can use an e-mail. The idea is to warn developers and users of potential data leaks if used.

**Comment by Spomky** [comment]
Closing as not relevant.
