### ISSUE TITLE
Yubikey Passkey not works

### ISSUE THREAD

**Issue by Nevercold** [web-auth/webauthn-framework#383]
### Version(s) affected

4.5.1

### Description

If I store a passkey such as Windows Hello or Apple Passkey, it is stored on the device and also works for passwordless logins.
The same with Yubikey does not seem to work, Windows says "This security key does not look known".

I don't know if it's me or if I did something wrong. Other users have the same problem on the website.
I know that it works with Yubikey, because I also use it with a software.

Thanks :)

### How to reproduce

https://gist.github.com/Nevercold/5e6fa1d32df0c13846ba839880a16035
The Json Options and small piece of code

### Possible Solution

Yubikey works for Passkeys (?)

**Comment by Nevercold** [comment]
nvm, if I set ->setRequireResidentKey(true); it works and also shows that it wants to store data on the key.
However, the function is deprecated and setResidentKey() is required, but in the json it is written as not required.
Is this a bug or normal

**Comment by Spomky** [comment]
Hello @Nevercold,

Actually, the library is a bit ahead of its time...
It is in line with the version 2 of the specification where `requireResidentKey` (a boolean) is kept for backwards compatibility with the version 1.
`residentKey` (string) is the new key to be used.
Unfortunately, web browsers do not seem to support this key while `requireResidentKey` is marked deprecated here.
Best option now is to have both keys in the options. What I could do is to set it as `requireResidentKey: true` when `residentKey`  is `required`.
WDYT?

EDIT: [section 5.4.4 of webauthn-2](https://www.w3.org/TR/webauthn-2/#dictionary-authenticatorSelection)

**Comment by Nevercold** [comment]
Okay, I didn't know that, so the two options are 2 "different" things, right?
Setting this to True would probably be the best option. There will always be some software that does not listen to the newer one yet
Thanks for fast help :)

**Comment by Spomky** [comment]
> Okay, I didn't know that, so the two options are 2 "different" things, right?

The purpose is the same, but it is now more explicit. `requireResidentKey` only tells you want to require a resident key. With the new option, you can specify if it is `discouraged`, `preferred` (default) or `required` and helps for selecting and using discoverable keys (with Passkey in mind).

> Setting this to True would probably be the best option. There will always be some software that does not listen to the newer one yet
Thanks for fast help :)

OK. I will modify the source code accordingly. This will induce a side effect, but seems to be a desirable one.

**Comment by Nevercold** [comment]
Perfect!
