### ISSUE TITLE
Support older PHP versions (7.4)

### ISSUE THREAD

**Issue by gruberroland** [web-auth/webauthn-framework#387]
### Description

I fully understand that you do not want to support very old PHP releases. But maybe it would be possible to support PHP 7.4 onward? There are lots of users that are still on that version.
From the code perspective it should be no big issue to support more versions.

Maybe support at least the last supported version of PHP + 6 months?

https://www.php.net/supported-versions.php

### Example

Support PHP from 7.4 onward instead of 8.1 onward.

**Comment by Spomky** [comment]
Hello @gruberroland,

> There are lots of users that are still on that version.

I understand that legacy projects are still using outdated PHP versions and is it sometime hard to move to the latest ones.
That is why the version 3.3.x supports PHP 7.2+ and will still [receive security updates](https://github.com/web-auth/webauthn-framework/security/policy) if any.
Note that no features or bugfixes will be made on this branch.

> From the code perspective it should be no big issue to support more versions.

It's not just about how this framework works. The issue for me is that security features like Webauthn should not rely on a platform that no longer receives security updates.
So the version 3.3.x will be maintained until PHP 8.0 reaches its end of life-, i.e. November 2023.

**Comment by gruberroland** [comment]
Thanks for the clarification. I was not aware that 3.3.x is still supported. :+1:
