### ISSUE TITLE
Easier PublicKeyCredentialSource creation

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-auth/webauthn-framework#39]
**Is your feature request related to a problem? Please describe.**
Currently there are many parameters for `__construct()` that could be obtained from `PublicKeyCredential`.

**Describe the solution you'd like**
Add a method to `PublicKeyCredential` for creation of `PublicKeyCredentialSource`

**Describe alternatives you've considered**
Have `__construct` ingest `PublicKeyCredential` for many of its parameters.

**Additional context**
Currently I'm doing something along the lines of:
```
$publicKeyCredential           = $publicKeyCredentialLoader->load(json_encode($data));
$publicKeyCredentialDescriptor = $publicKeyCredential->getPublicKeyCredentialDescriptor();
$response                      = $publicKeyCredential->getResponse();

$pkCredentialSource = new PublicKeyCredentialSource(
    $publicKeyCredentialDescriptor->getId(),
    $publicKeyCredentialDescriptor->getType(),
    $publicKeyCredentialDescriptor->getTransports(),
    $response->getAttestationObject()->getAttStmt()->getType(),
    $response->getAttestationObject()->getAttStmt()->getTrustPath(),
    $response->getAttestationObject()->getAuthData()->getAttestedCredentialData()->getAaguid(),
    $response->getAttestationObject()->getAuthData()->getAttestedCredentialData()->getCredentialPublicKey(),
    $this->getLoggedInUser($request)->_id->__toString(),
    0
);
```

As you can see, all but the last two parameters could be obtained internally by passing an attested `PublicKeyCredential`, user ID, and counter (that should be optional and default to 0)

**Comment by Spomky** [comment]
Yep. I noticed that when building the demo and the v1.1.
I will add a static method to ease the creation of a `PublicKeyCredentialSource` object from a `PublicKeyCredential` one.

**Comment by moderndeveloperllc** [comment]
Thanks. Not sure it can be static as lots of stuff coming from `$this->response` created by the loader, but which ever way you prefer would great.

**Comment by Spomky** [comment]
I was thinking of a function like this one (within the `PublicKeyCredentialSource` class - code not tested):

```php
public static function createFromPublicKeyCredential(PublicKeyCredential $publicKeyCredential, string $userHandle): self
{
    $response = $publicKeyCredential->getResponse();
    Assertion::isInstanceOf($response, AuthenticatorAttestationResponse::class, 'Creation is only possible using a public key credential containing an authenticator attestation response.');
    $publicKeyCredentialDescriptor = $publicKeyCredential->getPublicKeyCredentialDescriptor();

    return new self(
        $publicKeyCredentialDescriptor->getId(),
        $publicKeyCredentialDescriptor->getType(),
        $publicKeyCredentialDescriptor->getTransports(),
        $response->getAttestationObject()->getAttStmt()->getType(),
        $response->getAttestationObject()->getAttStmt()->getTrustPath(),
        $response->getAttestationObject()->getAuthData()->getAttestedCredentialData()->getAaguid(),
        $response->getAttestationObject()->getAuthData()->getAttestedCredentialData()->getCredentialPublicKey(),
        $userHandle,
        $response->getAttestationObject()->getAuthData()->getSignCount()
    );
}
```

That could be called like this:

```php
$credentialSource = PublicKeyCredentialSource::createFromPublicKeyCredential(
    $publicKeyCredential,
    $publicKeyCredentialCreationOptions->getUser()->getId()
);
```

**Comment by moderndeveloperllc** [comment]
That looks like a good idea. I mistook where you were planning on putting the function. I had also not seen `getSignCount()`.

**Comment by Spomky** [comment]
Done in https://github.com/web-auth/webauthn-framework/commit/06eb230959028ac7715d814cdfc48c6129805852

Let me know if you see anything that could be improved.
This method only works during the attestation ceremony, I don't think it is necessary to add a method for other use cases as the pk credential sources are supposed to be generated during this ceremony.

**Comment by moderndeveloperllc** [comment]
Looks good and makes creation much easier.

One thing that might be nice is to have set*() methods for all the class variables. As this is the class that is designed to be stored in databases, it might be necessary to manipulate the values during the roundtrip (the three `string`s that are binary for example - `$publicKeyCredentialId`, `$aaguid`, `$credentialPublicKey`).

In my use case I'm using MongoDB, so if I want to store this as an object I need to `extend` the class with my serialization/deserialization methods, but right now I can't set the `private` vars on deserialization.

**Comment by Spomky** [comment]
There is no setter in the classes to avoid unexpected behaviour due to object manipulations and because these values should be modified.
I understand that this can be very frustrating, but there’s always a way to handle that without any setter.

In the v1.1 branch I added some [Doctrine custom types](https://github.com/web-auth/webauthn-framework/tree/v1.1/src/symfony/src/Doctrine/Type) and [mapped properties for ORM](https://github.com/web-auth/webauthn-framework/blob/v1.1/src/symfony/src/Resources/config/doctrine-mapping/PublicKeyCredentialSource.orm.xml) thus storage in DB using Doctrine is very simple.
Something similar could be added for MongoDB and ODM using the [inheritance mapping](https://www.doctrine-project.org/projects/doctrine-mongodb-odm/en/1.2/reference/inheritance-mapping.html).

For other use cases (i.e. without Doctrine), you need to extend the classes.
What about the `\JsonSerializable` interface? That could be a way to ease the serialization of the object.

**Comment by moderndeveloperllc** [comment]
Making the class `\JsonSerializable` with the attendant methods would help as that would take care of the binary string roundtrips.

I'm not using Doctrine as MongoDB has a very nice [`Persistable`](http://php.net/mongodb-bson-persistable) interface and [userland library](https://github.com/mongodb/mongo-php-library). I also don't have dozens of collections, so that means I can skip the ORM.

I can figure it out either way to do what I need to do. Thanks!

**Comment by Spomky** [comment]
Hi @moderndeveloperllc,

I revised my mind and change the visibility of some class properties from private to protected.
Let me know if you see other classes that may be updated too.
