### ISSUE TITLE
WebAuthn.php is missing

### ISSUE THREAD

**Issue by Steepe** [web-auth/webauthn-framework#391]
### Version(s) affected

3.3.12

### Description

This file (WebAuthn.php) is missing.

### How to reproduce

download the library and you will notice.

**Comment by Spomky** [comment]
Not sure to clearly understand what you want here...

**Comment by Steepe** [comment]
How do I get the missing file? I am trying to get the WebAuthn object

$webauthn = new Webauthn();

I am importing this  use Webauthn\Webauthn;

However the Webauthn.php does not exist. Please advise.

**Comment by Spomky** [comment]
It does not miss. It simply does not exist and never has.
Please have a look at [the documentation first](https://webauthn-doc.spomky-labs.com/v/v3.3/the-webauthn-server/the-easy-way) (note that the current major branch is `4.x` ad not `3.x`).

**Comment by Steepe** [comment]
Thank you for this. I was following a tutorial provided by ChatGPT on webauthn integration into Codeigniter 4. ChatGPT kept on insisting on the use of that file.  Thank you for your time. Do you by chance have a tutorial page I can follow through?

**Comment by Spomky** [comment]
Hi,

I found one here: https://www.youtube.com/watch?v=aSC7OaBP69k
It is in French, but subtitles are available.
