### ISSUE TITLE
AuthenticatorAssertionResponse expects userHandle to be regular base64

### ISSUE THREAD

**Issue by TimWolla** [web-auth/webauthn-framework#392]
### Version(s) affected

4.5.1

### Description

The `AuthenticatorAssertionResponse::getUserHandle()` method uses `ParagonIE\ConstantTime\Base64` instead of `Webauthn\Util\Base64` and thus expect the userHandle to be in regular base64, rejecting URL safe base64.

### How to reproduce

Attempt to load a response with a URL-safe base64 encoded userHandle. 

### Possible Solution

Use `Webauthn\Util\Base64` instead. 

### Additional Context

The JavaScript encoding the response is a custom JavaScript. The WebAuthn key is the macOS Keychain with a randomly generated userHandle. The encoded contained the `-` character which is `+` in regular base64

```
0 ParagonIE\ConstantTime\Base64::decode('mS9urk3F4Q2JTB2t5fJhd-r50y8lenNOTgRVwhvO3Mk', true)
vendor/web-auth/webauthn-lib/src/AuthenticatorAssertionResponse.php:39
#1 Webauthn\AuthenticatorAssertionResponse->getUserHandle()
vendor/web-auth/webauthn-lib/src/AuthenticatorAssertionResponseValidator.php:113
#2 Webauthn\AuthenticatorAssertionResponseValidator->check('��c�������:�E�7u,`�1(CEZ$��c��', Webauthn\AuthenticatorAssertionResponse, Webauthn\PublicKeyCredentialRequestOptions, Laminas\Diactoros\ServerRequest, '�/n�M�� �L����aw��/%zsNN�U�����')
```

Furthermore there is a second related second bug: An invalid `userHandle` should probably throw an `InvalidDataException` during loading of the response in `PublicKeyCredentialLoader::createResponse()`. Currently a `RangeException` is thrown when `AuthenticatorAssertionResponse::getUserHandle()` is called internally. This is inconsistent.

**Comment by Spomky** [comment]
Hi @TimWolla,

OK for the inconsistency of the exception type. I agree with you and this should be changed.
For the userHandle encoding, the reason is that tests against the [FIDO Alliance conformance tool](https://github.com/fido-alliance/conformance-test-tools-resources) did not pass when base64url safe encoded.
That is why I abandoned my custom made client library in favor of [@simplewebauthn/browser](https://simplewebauthn.dev/docs/packages/browser/), which is also [compliant](https://github.com/herrjemand/awesome-webauthn#client-libs).

**Comment by TimWolla** [comment]
Thank you for your response. I'm not quite sure I follow with regard to the conformance testing. Isn't the encoding between the JS client and the PHP server something that is specifically agreed between both of them? The native browser API just gives you some Buffer, how you transmit the Buffer to the server is up to you, no?

In fact the simplewebauthn/browser library does not use base64 at all. Instead it encodes the userHandle as UTF-8: https://github.com/MasterKale/SimpleWebAuthn/blob/7cbc1dc6723294874fe4f576c2d32d07337ec5af/packages/browser/src/methods/startAuthentication.ts#L94. To my understanding this is incorrect, because the user handle is an opaque byte sequence that is not necessarily valid UTF-8: https://www.w3.org/TR/webauthn-2/#user-handle

Within the “User Agent Automation” section the “Add Credential” endpoint expects the userHandle to be in base64url: https://www.w3.org/TR/webauthn-2/#sctn-automation-add-credential

**Comment by TimWolla** [comment]
In fact github/webauthn-json also expects the userHandle to be base64url: https://github.com/github/webauthn-json/blob/2b67bdbc93c7eb245abc21fb23df6f68eed643ee/src/webauthn-json/basic/json.ts#L124

**Comment by Spomky** [comment]
OK. So let's fix that. It could be interesting to allow customizing the way the data is transmitted to the server. WDYT?

**Comment by TimWolla** [comment]
> It could be interesting to allow customizing the way the data is transmitted to the server. WDYT?

I think just url-safe base64 is fine. That allows to reliably transmit all types of binary data and is easily implemented with JavaScript. Hex encoding would be much more complicated and UTF-8 does not support arbitrary opaque bytes.

The issue really is that userHandle currently expects regular base64, instead of url-safe, as you (accidentally?) directly used the constant time encoder, instead of your helper class.

**Comment by Spomky** [comment]
OK. Modifications merged.
