### ISSUE TITLE
Exception: createAuthenticatorAssertionResponseValidationFailedEvent(): Argument #1 ($credentialId) must be of type string

### ISSUE THREAD

**Issue by tomsommer** [web-auth/webauthn-framework#418]
### Version(s) affected

4.6.1

### Description

Uncaught Exception TypeError: "Webauthn\AuthenticatorAssertionResponseValidator::createAuthenticatorAssertionResponseValidationFailedEvent(): Argument #1 ($credentialId) must be of type string, Webauthn\PublicKeyCredentialSource given, called in /var/www/example.com/vendor/web-auth/webauthn-lib/src/AuthenticatorAssertionResponseValidator.php on line 307" at /var/www/example.com/vendor/web-auth/webauthn-lib/src/AuthenticatorAssertionResponseValidator.php line 365

### How to reproduce

Unsure, but it's related to #384

**Comment by Spomky** [comment]
I have just tagged 4.6.2 that should fix this issue.
