### ISSUE TITLE
AbstractTrustPath::createFromJson() should accept string

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-auth/webauthn-framework#42]
**Is your feature request related to a problem? Please describe.**
The method `createFromJson()` by its name would seem to indicate that you pass JSON to it, but in actuality you need to pass an array.

**Describe the solution you'd like**
Either allow method to consume either array or JSON string, or only string

**Comment by Spomky** [comment]
Hi @moderndeveloperllc,

That’s right the name of the method is not clear.
I’ve just created a PR to fex that. See #43.

**Comment by moderndeveloperllc** [comment]
LGTM

**Comment by Spomky** [comment]
Merged. Thank you. Will be tagged soon
