### ISSUE TITLE
Conflict with StimulusBundle

### ISSUE THREAD

**Issue by fendrychl** [web-auth/webauthn-framework#428]
### Version(s) affected

4.6.x

### Description

Hello,

I encountered a problem when "Webauthn\Stimulus\WebauthnStimulusBundle" is registered in bundles.php after "Symfony\UX\StimulusBundle\StimulusBundle" (this is related to #409). Both bundles have "StimulusExtension" class a I not sure why, but it is a problem. When "Webauthn\Stimulus\WebauthnStimulusBundle" is registered after StimulusBundle - StimulusBundle cannot load its configuration (services.php etc - whole load function in StimulusExtension is not called). When I move "Webauthn\Stimulus\WebauthnStimulusBundle" move before StimulusBundle, everything works again (but I'm not sure about WebauthnStimulusBundle's StimulusExtension class, because I use webpack instead of AssetMapper. When I rename WebauthnStimulusBundle's StimulusExtension to Stimulus2Extension, everything works too and WebauthnStimulusBundle can be registered after StimulusBundle.

I will be happy if someone verifies this issue. But probably the name of the extension should be unique.

Thank you.

### How to reproduce

Install symfony/stimulus-bundle and web-auth/webauthn-stimulus. Verify "Webauthn\Stimulus\WebauthnStimulusBundle" is registered after "Symfony\UX\StimulusBundle\StimulusBundle" in bundles.php. Then you should see problems with StimulusBundle (not registered stimulus.helper service - no twig stimulus_* functions).

### Possible Solution

Rename StimulusExtension to something else - maybe to WebauthnStimulusExtension.

**Comment by Spomky** [comment]
Hi,

This is fixed with 4.6.1.
Can you confirme you are using the latest version ?

**Comment by fendrychl** [comment]
Thank you for fast response. Yes, I have the latest version - 4.6.2.

**Comment by Spomky** [comment]
I have just renamed the extension.
It looks like the issue comes from `Symfony\Component\HttpKernel\Bundle\Bundle::getContainerExtension()` that register the same extension twice, but I am not 100% sure at the moment.
This seems fine with `4.6.3`. Feel free to reopen if it is not the case.
Many thanks.
