### ISSUE TITLE
InvalidArgumentException decodeNoPadding() doesn't tolerate padding for clientDataJSON

### ISSUE THREAD

**Issue by jmalinens** [web-auth/webauthn-framework#457]
### Version(s) affected

4.6.4

### Description

I am in process of upgrading from 3.x to 4.x. Was not easy for me  but I am almost done!

stack trace:

```php
array (
  0 => 
  array (
    'file' => 'vendor/web-auth/webauthn-lib/src/PublicKeyCredentialLoader.php',
    'line' => 141,
    'function' => 'createFormJson',
    'class' => 'Webauthn\\CollectedClientData',
    'type' => '::',
  ),
  1 => 
  array (
    'file' => 'vendor/web-auth/webauthn-lib/src/PublicKeyCredentialLoader.php',
    'line' => 81,
    'function' => 'createResponse',
    'class' => 'Webauthn\\PublicKeyCredentialLoader',
    'type' => '->',
  ),
  2 => 
  array (
    'file' => 'vendor/web-auth/webauthn-lib/src/PublicKeyCredentialLoader.php',
    'line' => 105,
    'function' => 'loadArray',
    'class' => 'Webauthn\\PublicKeyCredentialLoader',
    'type' => '->',
  ),
  3 => 
  array (
    'file' => 'vendor/web-auth/webauthn-symfony-bundle/src/Controller/AttestationResponseController.php',
    'line' => 66,
    'function' => 'load',
    'class' => 'Webauthn\\PublicKeyCredentialLoader',
    'type' => '->',
  ),
  4 => 
  array (
    'file' => 'vendor/symfony/http-kernel/HttpKernel.php',
    'line' => 166,
    'function' => '__invoke',
    'class' => 'Webauthn\\Bundle\\Controller\\AttestationResponseController',
    'type' => '->',
  ),
)
```

client (latest Firefox) sends clientDataJSON with padded `==` but code requires unpadded string.

`$data =  rtrim($data, '='); ` helps in `vendor/web-auth/webauthn-lib/src/CollectedClientData.php:85` but there should be more proper solution.

I am using `@web-auth/webauthn-helper` 0.0.13

other option is to change npm module and right trim `=` character in `node_modules/@web-auth/webauthn-helper/src/common.js`

### How to reproduce

Add new device

**Comment by jmalinens** [comment]
@Spomky never mind I just figured out https://github.com/MasterKale/SimpleWebAuthn is replacement for that JS library. will try to implement it!

**Comment by Spomky** [comment]
Yes indeed the JS library has been deprecated in favor of SimpleWebAuthn.
I close this issue, but feel free te reopen if deemed necessarry
