### ISSUE TITLE
The attestation statement format "none" is not supported.

### ISSUE THREAD

**Issue by Jorgu5** [web-auth/webauthn-framework#472]
### Version(s) affected

4.7.0

### Description

With whatever authorization type I use on MacOS Ventura, either Safari / Firefox / Chrome browser, I am getting either 

**The attestation statement format "none" is not supported.** or  **The attestation statement format "packed" is not supported.** depends on if I use in the _ATTESTATION_CONVEYANCE_PREFERENCE_NONE_ or _ATTESTATION_CONVEYANCE_PREFERENCE_DIRECT_ 

The error is returned from the line where credential are loaded => `$this->public_key_credential_loader->load( $data )`

Here is my initial class handler for registration flow => https://gist.github.com/Jorgu5/31ce1c053382ff8cb59825f4ea4879c9

I am using @SimpleWebAuthn on the front-end. 

Here is the object I am getting back from authenticator and loading a.k.a $data https://gist.github.com/Jorgu5/23035765855f91a594e92058bbd976fe 

### How to reproduce

Described above. Login without username using hardware authenticator. Tested also several other hardware tools like usb on Chrome through Webauthn DevTools emulator but it's the same. 

### Possible Solution

Completely have no idea. -.-

### Additional Context

Working on localhost without SSL. However the code breaks before the attestation validator what's outlined here https://webauthn-doc.spomky-labs.com/pure-php/advanced-behaviours/dealing-with-localhost

**Comment by Spomky** [comment]
Hi,

The Attestation `StatementSupportManager` requires at least one `AttestationStatementSupport` (https://webauthn-doc.spomky-labs.com/pure-php/the-hard-way#supported-attestation-statement-types)

```php
<?php

declare(strict_types=1);

use Webauthn\AttestationStatement\AttestationStatementSupportManager;
use Webauthn\AttestationStatement\NoneAttestationStatementSupport;

// The manager will receive data to load and select the appropriate 
$attestationStatementSupportManager = AttestationStatementSupportManager::create()
    ->add(NoneAttestationStatementSupport::create())
;
```

It should be added right after https://gist.github.com/Jorgu5/31ce1c053382ff8cb59825f4ea4879c9#file-class-registration-handler-php-L168

By the way, I think `none` will be added by default to avoid such misunderstanding

**Comment by Jorgu5** [comment]
Damn, what an oversight from my side. Thank you for reviewing my code and prompt response, everything works properly now.
