### ISSUE TITLE
How to implement registration when using Passkeys with email as user handle?

### ISSUE THREAD

**Issue by nicodemuz** [web-auth/webauthn-framework#477]
### Description

My goal is to implement Passkeys registration using an email address and name, as below:
![image](https://github.com/web-auth/webauthn-framework/assets/1620454/225083a7-b72f-44e7-b0f0-a1ff2b914155)

I already have implemented adding a Passkey to an existing account and login using it, which works fine. In this case, the `public_key_credential_sources` table contains the email address in the `user_handle` column.

Now that I'm implementing the registration form for new users, I'm unable to get the `user_handle` column to contain the registered email address. Instead it becomes a generated user ID that is likely done by this function:
```php
    public function generateNextUserEntityId(): string
    {
        return Ulid::generate();
    }
```

I would like to save the email address in the `user_handle` column instead of a newly generated ID. How should I proceed to implement this?

My User entity has only `id` and `email` fields like below:
```php
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\Email]
    #[Assert\NotBlank]
    private string $email;
```

**Comment by nicodemuz** [comment]
I think I was able to get it working with the following hack (need to test further):
```php
    public function generateNextUserEntityId(): string
    {
        $request = $this->requestStack->getCurrentRequest();

        $content = $request->getContent();

        $dto = $this->serializer->deserialize(
            $content,
            ServerPublicKeyCredentialCreationOptionsRequest::class,
            'json'
        );

        return $dto->username;
    }
```

A better approach is to probably write a custom guesser that doesn't use the `generateNextUserEntityId()` call.

**Comment by Spomky** [comment]
Hi,

Since 4.7.0, the method `generateNextUserEntityId` is deprecated.
Your repository should implement `Webauthn\Bundle\Repository\CanGenerateUserEntity`.
This interface has only one method `public function generateUserEntity(?string $username, ?string $displayName): PublicKeyCredentialUserEntity;`.
You can simply return the object you want with the email as handle.

**Comment by nicodemuz** [comment]
Thanks for your help @Spomky.

If I replace the CanRegisterUserEntity interface with CanGenerateUserEntity interface, I get the following error in here:
https://github.com/web-auth/webauthn-framework/blob/4.7.x/src/symfony/src/Security/Http/Authenticator/WebauthnAuthenticator.php#L240

Do I need to implement both interfaces?

![image](https://github.com/web-auth/webauthn-framework/assets/1620454/9728962a-2486-4a1d-8316-b9d496799328)

**Comment by nicodemuz** [comment]
Ok, it seems to work if I implement both interfaces. Thanks!

**Comment by Spomky** [comment]
Hi,

Yes the interface should be kept for backward compatibility. Only part of it is deprecated (method `generateNextUserEntityId`).

**Comment by Spomky** [comment]
Also, please note that the use of an email address as user handle is not recommended (see https://www.w3.org/TR/webauthn-2/#sctn-user-handle-privacy).
I recommended you generate a random unique immuable user handle you associate to each user.

**Comment by Spomky** [comment]
Closing as resolved.
Feel free to open again if deemed necessary.
Thanks.
