### ISSUE TITLE
`PublicKeyCredentialCreationOptions::create()` is marked as `@private`

### ISSUE THREAD

**Issue by TimWolla** [web-auth/webauthn-framework#481]
I don't think this is intentional, because both the `__construct()` and `create()` are `@private`:

https://github.com/web-auth/webauthn-framework/blob/fbdcf7342bc0e993c750839b785090761a0b5522/src/webauthn/src/PublicKeyCredentialCreationOptions.php#L78

**Comment by Spomky** [comment]
Indeed. My mistake.
I will fix that.

**Comment by Spomky** [comment]
Closing as resolved.
Will be fixed in 4.7.2.
