### ISSUE TITLE
Do not deprecate the support for PSR-18 HTTP clients

### ISSUE THREAD

**Issue by TimWolla** [web-auth/webauthn-framework#482]
### Description

During upgrading the library for our use, I came across

https://github.com/web-auth/webauthn-framework/blob/fbdcf7342bc0e993c750839b785090761a0b5522/src/metadata-service/src/Service/DistantResourceMetadataService.php#L41-L47

While we do not currently make use of the metadata service and thus are not affected by the deprecation directly, this deprecation would be problematic for our non-Symfony application. In our case Guzzle is the HTTP client of choice and we have functionality for a properly configured Guzzle client that makes use of an outgoing HTTP proxy and sets proper timeouts. This functionality would need to be duplicated for the Symfony client in addition to pulling in another dependency.

Based on the [Packagist metadata](https://packagist.org/packages/symfony/http-client) it appears that the Symfony client also provides a PSR-18 interface (psr/http-client-implementation).

Would it be an option for you to not deprecate the support for PSR-18 clients? Perhaps even the Symfony logic could be removed and everything unified to PSR-18, while still supporting the Symfony client?

**Comment by Spomky** [comment]
HI.

Ok I understand the problem.
I wanted to get rid of the PSR-xx (to me: too complex for just HTTP calls).
What I can do is provide a class for PSR-xx support and another for symfony/http-client.

**Comment by Spomky** [comment]
A class is now provided by the library. It allows PSR Client to be used.
