### ISSUE TITLE
The documentation is severely out of date

### ISSUE THREAD

**Issue by kamil-tekiela** [web-auth/webauthn-framework#486]
### Version(s) affected

4.7

### Description

I am trying to implement webauthn using this library. I installed the library and tried to follow the documentation. I observed that many functions are marked as deprecated. On top of that, many examples are either broken or incomplete. It's impossible to follow the documentation with the current version of this library. 

Some examples:
- https://webauthn-doc.spomky-labs.com/pure-php/authenticate-your-users#user-verification Why is there `$allowedCredentials` if it's not used in that example.
- https://webauthn-doc.spomky-labs.com/pure-php/authenticate-your-users#response-verification uses variable `$userHandle` that doesn't seem to be set up anywhere of explained what it is. 
- https://webauthn-doc.spomky-labs.com/pure-php/authenticate-your-users#example example uses `findAllForUserEntity()` with `$userEntity` and neither is explained what it is or what is its purpose.
- https://webauthn-doc.spomky-labs.com/pure-php/the-hard-way#supported-attestation-statement-types example uses method chaining with a method `add()` that is not a chainable method. 

### How to reproduce

Copy the examples into IDE and see highlighted errors and deprecations.

**Comment by Spomky** [comment]
Hi,

Thank you for this report. The documentation is up to date and all your comments are now fixed.

Regards.
