### ISSUE TITLE
Paramater `residentKey` will be ignored when Initializing AuthenticatorSelectionCriteria

### ISSUE THREAD

**Issue by tomocrafter** [web-auth/webauthn-framework#516]
### Version(s) affected

4.7.4

### Description

Paramater `residentKey` will be ignored when Initializing AuthenticatorSelectionCriteria

### How to reproduce

`new AuthenticatorSelectionCriteria(null, "preferred", "required")->residentKey;`

### Possible Solution

This line should be `$this->residentKey = $residentKey !== null ? $residentKey : ($requireResidentKey === true ? self::RESIDENT_KEY_REQUIREMENT_REQUIRED : self::RESIDENT_KEY_REQUIREMENT_PREFERRED);`
https://github.com/web-auth/webauthn-framework/blob/d7b7eb73bc017c636f2bcf3b14ade11c3691cc0b/src/webauthn/src/AuthenticatorSelectionCriteria.php#L80

**Comment by Spomky** [comment]
Hi,

Indeed, there is something wrong with this line.
I will address this issue ASAP

**Comment by tomocrafter** [comment]
Hi, Thank you for response and commiting to this great library! It was hard to find solid library for webauthn in PHP so I am so pleasure to meet to this.

Thank you for looking into this problem as well, I think this can be fixed by my suggestion so Can I open the pull request with these changes?

**Comment by Spomky** [comment]
Done. Will be tagged soon
