### ISSUE TITLE
Compatibility with php 7.4?

### ISSUE THREAD

**Issue by developer-betandeal** [web-auth/webauthn-framework#539]
### Description

I need to implement webauthn in a php 7.4 powered site (changing to php 8 is not an option for now). I would fork the repo and make the modifications needed by myself. There are some dependencies out of this repo incompatible with php 4.7?

**Comment by Spomky** [comment]
Hi,

The framework follows the major PHP versions and now PHP versions below 8.1 are not supported anymore.
Si it is quite difficult to answer this question and the answer that first comes is "no", but try it as it may work with a previous major release. For a security feature like this, this is not something we recommend in all cases, but for experimenting on a non-critical system it is still possible.

**Comment by developer-betandeal** [comment]
I understand, but there are a lot of very complex systems that cannot just upgrade to php8 and they needs to be able to use webauthn.  I don't know if it would be easiest to create a microservice to do the job (calling to obtain the options / check the responses) written in any other up-to-date languaje or to make this work on php7.4.

**Comment by Spomky** [comment]
Indeed, if you use it with an independent application you solve your issue.
