### ISSUE TITLE
'Invalid signature' as result of authentication

### ISSUE THREAD

**Issue by justewg** [web-auth/webauthn-framework#57]
I've tried to implement solution, written in examples of two steps.
Actually, everything works great except the one step, the last and main :)

**To Reproduce**
I create my own CredentialRepository class with such method:
```
public function findOneByCredentialId(string $publicKeyCredentialId): ?PublicKeyCredentialSource
    {
        $user = MongoUser::getByFieldValue(
            'webauthn_pkc_source.publicKeyCredentialId',
            Base64Url::encode($publicKeyCredentialId)
        );

        if ($user !== null) {
            $credentials = $user->webauthn_pkc_source;
            $res = PublicKeyCredentialSource::createFromArray($credentials);
        }

        return $res;
    }
```
So, my created Public Key Credential Source object writes to users account in MongoDB and finds from DB in this method, if finded - returns as PublicKeyCredentialSource object.

In credentials validation procedure I run method check():
```
// Check the response against the attestation request
            $authenticatorAssertionResponseValidator->check(
                $publicKeyCredential->getRawId(),
                $publicKeyCredential->getResponse(),
                $publicKeyCredentialRequestOptions,
                $psr7Request,
                null // User handle
            );
```
and in returns an error of step 7.2.16 of checkings, `$this->algorithmManager` is null

**Expected behavior**
Of course, I've expected that check() returns true and authentication completes.

**Desktop/Smartphone (please complete the following information):**
 - OS: Mac OS Mojave 10.14.4 
 - Browser Chrome
 - Version 74.0.3729.169

**Additional context**
I suppose that, may by, I send to check procedure the wrong saved object. I save this object with credential info on second step of making credentials, actually:
```
        // You can get the Public Key Credential Source. This object should be persisted using the Public Key Credential Source repository
        $publicKeyCredentialSource = \Webauthn\PublicKeyCredentialSource::createFromPublicKeyCredential(
            $publicKeyCredential,
            $publicKeyCredentialCreationOptions->getUser()->getId()
        );

        MongoUser::update(
            (int)$publicKeyCredentialCreationOptions->getUser()->getId(),
            array_merge(
                ['webauthn_pkc_source' => json_decode(json_encode($publicKeyCredentialSource), true)]
            )
        );
```

**Comment by Spomky** [comment]
Hi, thank you for this report.
Can you share an example of the data you store and an authenticator assertion?
What type of authenticator do you use? Built-in fingerprint reader on MacBook Pro, USB key or anything else?

By the way, instead of `json_decode(json_encode(...))` you can use `$publicKeyCredentialSource->jsonSerialize()`

**Comment by justewg** [comment]
Ok, thanks for point to `jsonSerialize()`

Something like this:
![image](https://user-images.githubusercontent.com/16482115/58950421-6b35a500-8797-11e9-819c-6f1e9bcf31c4.png)

Thanks for quick response

**Comment by Spomky** [comment]
OK. Is et possible to get one record as text that I copy/paste?
I also need an assertion and the associated options. 

Can you test if it works wish the demo (https://webauthn.spomky-labs.com). If it fails, the error may come from the library itself. Otherwise I need to investigate deeper.

**Comment by justewg** [comment]
OK, I'll send json string below.
Actually, if I use `$publicKeyCredentialSource->jsonSerialize()`, the parameter trustPath in my case returns as empty array and there is an error in `PublicKeyCredentialSource::createFromArray($credentials);` because it expect {type:'empty'}
But `json_decode(json_encode())` returns correct trustPath

**Comment by justewg** [comment]
```
{"publicKeyCredentialId":"AG1dhBPuRhDPlfoFDGKnjnniCgLB7k4n_ogfzdjin4VSeu_ytc2YKfxfCRgLG58Xn03oWIJT8hB4eSZloGbOKcYMVVQvdkvdGf9O","type":"public-key","transports":[],"attestationType":"none","trustPath":{"type":"empty"},"aaguid":"rc4AAjW8xgpkiwsl8fBVAw","credentialPublicKey":"pQECAyYgASFYIJnA9jpVFs-1tx9eQxPIXao1WGIVxLP9YbiETU_opGREIlggDcj_4eG3UJxBo9jqswVa0nMzwSLbnESHquEzcnLXn7g","userHandle":"NjY","counter":1559743445}
```

**Comment by justewg** [comment]
What objects do you need more? `PublicKeyCredentialCreationOptions` ?

**Comment by justewg** [comment]
And what should I test on your host ? `Webauthn Demo` on this page doesn't do anything

**Comment by Spomky** [comment]
There is a menu where you can create an account and login.
If there is something wrong I will receive a notification.

**Comment by justewg** [comment]
I choose option of built-in fingerprint scanner, but then I receive a message about checking usb-key manufacturer.

**Comment by Spomky** [comment]
I’ve just released `v1.2.2` that fixes a bug when key are loaded using the method `createFromArray`.
Can you update your depndencies and let me know if it works fine?

I don’t know why the demo doesn’t allow you to use the fingerprint.
I also updated it with v1.2.2 and will test it again soon.

**Comment by Spomky** [comment]
Hi @justewg , is there any news. Did the last release fix the issue?

**Comment by justewg** [comment]
Works great now, thanks!

**Comment by Spomky** [comment]
Excellent. Thank you.
