### ISSUE TITLE
Incorrect deprecations

### ISSUE THREAD

**Issue by bobvandevijver** [web-auth/webauthn-framework#572]
### Version(s) affected

4.8.0

### Description

The [`PublicKeyCredentialLoader`](https://github.com/web-auth/webauthn-framework/blob/4.8.x/src/webauthn/src/PublicKeyCredentialLoader.php) has two kinds of deprecations: one which states that the complete class will disappear, and one that implies that the class will still be available (both deprecations started in 4.8, and target 5.0).

### How to reproduce

Check the deprecations in https://github.com/web-auth/webauthn-framework/blob/4.8.x/src/webauthn/src/PublicKeyCredentialLoader.php.

### Possible Solution

Either fully deprecate the class (and update the docs accordingly, see also #570) and update the deprecation messages (even remove the once that mention changed behaviour for 5.0), or undeprecate the class.

**Comment by Spomky** [comment]
Hello @bobvandevijver,

Indeed, the class is now deprecated but the other deprecation notices are very confusing.
This will be fixed.
