### ISSUE TITLE
How/where to report a security issue?

### ISSUE THREAD

**Issue by reedy** [web-auth/webauthn-framework#573]
### Description

I haven't got one to report, but...

https://github.com/web-auth/webauthn-framework/blob/c9e54b7/README.md#L40-L44

>If you discover a security vulnerability within the project, please **don't use the bug tracker and don't publish it
publicly**.
>Instead, all security issues must be sent to security [at] spomky-labs.com.

But if you go to https://github.com/web-auth/webauthn-framework/issues/new/choose "Report a security vulnerability" is also enabled. Are both valid? Or should people be using one or the other? Can it be clarified in the Readme? :)

https://github.com/web-auth/webauthn-framework/blob/c9e54b7/SECURITY.md similarly suggests to email, not mentioning the GitHub form

**Comment by Spomky** [comment]
Hello @reedy,

Than you for pointing this out. I will update those pages.
You can use the GH [Security Advisories](https://github.com/web-auth/webauthn-framework/security/advisories).

**Comment by Spomky** [comment]
Hi,

I modified the README page accordingly. Also, the documentation is up to date and lead to the same page.

Regards.
