### ISSUE TITLE
Supported versions?

### ISSUE THREAD

**Issue by reedy** [web-auth/webauthn-framework#574]
### Description

I can't see it anywhere obvious at least, as to which versions of this framework are still supported.

Is 3.x considered EOL? Or would bug reports (and/or security reports) be accepted?

The reason I ask, is potentially wanting to backport a couple of changes from 4.x into 3.x, but whether they'd be accepted (and ideally, released for use) is unclear.

Thanks!

**Comment by Spomky** [comment]
Hello @reedy,

Supported versions are mentioned in [the security page](https://github.com/web-auth/webauthn-framework/security/policy#supported-versions).
Indeed, 3.x is not maintained anymore. However, security reports are always welcomed, even on old releases.

**Comment by reedy** [comment]
https://github.com/web-auth/webauthn-framework/security/policy#supported-versions -> https://github.com/web-auth/webauthn-framework/blob/4.8.x/RELEASES.md

I somehow managed to miss that!

Can we get it linked from the main readme, so it's more obvious? 👍 Happy to do a PR for it later on

**Comment by Spomky** [comment]
Hi,

I updated the README page that the supported versions has a dedicated section.
I close this issue. Feel free to reopen if necessary.

Regards.

**Comment by reedy** [comment]
Perfect, thanks!
