### ISSUE TITLE
Incorrect serialization of PublicKeyCredentialSource

### ISSUE THREAD

**Issue by notapseudonym** [web-auth/webauthn-framework#58]
Hi,

`PublicKeyCredentialSource` does not "fully" serialize correctly; this has already shortly been mentioned here: https://github.com/web-auth/webauthn-framework/issues/57#issuecomment-499097525

Here's an example to show the problem:
```
$json0 ='{"publicKeyCredentialId":"5ZYF8upZZUFfw3ot0gkKOqcdIcSlem2P_oOcVrk_fVAhr6SqYFdG5TprFl336gjG-i5fefSsP8S5YFKI9Jee8A","type":"public-key","transports":[],"attestationType":"none","trustPath":{"type":"empty"},"aaguid":"AAAAAAAAAAAAAAAAAAAAAA","credentialPublicKey":"pQECAyYgASFYIHt5_B-asO10TT0pl5RDfljYMoEU_hSXAjxrnup_eX-uIlgg3AuFH37_CH6ntpD61_D8LqUBJ5bVY4vNPml0ZbtTeg4","userHandle":"YW5vdGhlci11bmlxdWUtaWQ","counter":0}';

// ok
$source1 = PublicKeyCredentialSource::createFromArray(json_decode($json0, true));

// workaround:
$source2 = PublicKeyCredentialSource::createFromArray(json_decode(json_encode($source1), true));

// that's how it supposedly should work, but doesn't
$source3 = PublicKeyCredentialSource::createFromArray($source1->jsonSerialize());
```

It seems like this can easily be fixed by pulling `JsonSerializable` from `AbstractTrustPath` to `TrustPath`, and fixing https://github.com/web-auth/webauthn-framework/blob/8832b3a9f83ceba3e446f23f9debfae567da6254/src/webauthn/src/PublicKeyCredentialSource.php#L221

to be:
`
            'trustPath' => $this->trustPath->jsonSerialize(), 
`

... but I'm not sure if this would be the preferred solution.

**Comment by Spomky** [comment]
Hi,

In fact I am not really happy with the design of the TrustPath objects.
I will find another way to serialize and load those objects.

I cannot modify the `TrustPath` interface without BC break.

**Comment by Spomky** [comment]
Done in v2.0
