### ISSUE TITLE
Incorrect message for PropertyInfoExtractor

### ISSUE THREAD

**Issue by ptmkenny** [web-auth/webauthn-framework#580]
### Version(s) affected

4.8.x

### Description

When trying to get this working on Drupal 10, I get the following error:

        "data": "The class \"Symfony\\Component\\PropertyInfo\\PropertyInfoExtractor\" is required. Please install the package \"symfony/serializer\" to use this feature."

However, this makes no sense because Drupal includes Symfony Serializer.

### How to reproduce

See above.

### Possible Solution

According to https://symfony.com/doc/current/components/property_info.html, the correct package for PropertyInfoExtractor is `symfony/property-info`.

**Comment by Spomky** [comment]
Hello @ptmkenny,

Yes indeed. This was fixed by #576. The fix is available in 4.8.3.

**Comment by ptmkenny** [comment]
Whoops, sorry for the duplicate report  I guess I started work just a couple hours too early before the release.
