### ISSUE TITLE
Missing dependency - phpdocumentor/reflection-docblock

### ISSUE THREAD

**Issue by arokettu** [web-auth/webauthn-framework#629]
### Version(s) affected

4.8.6, 4.9.0

### Description

Using raw webauth-lib generates these errors:

LogicException
Unable to use the "Symfony\Component\PropertyInfo\Extractor\PhpDocExtractor" class as the "phpdocumentor/reflection-docblock" package is not installed. Try running composer require "phpdocumentor/reflection-docblock".

### How to reproduce

```php
<?php

use Webauthn\AttestationStatement\AttestationStatementSupportManager;
use Webauthn\Denormalizer\WebauthnSerializerFactory;

(new WebauthnSerializerFactory(new AttestationStatementSupportManager()))->create();
```

### Possible Solution

Move phpdocumentor/reflection-docblock requirement from web-auth/webauthn-symfony-bundle to web-auth/webauthn-lib

**Comment by Spomky** [comment]
Hi @arokettu,

This dependency is not mandatory for the 4.x branchs. Either you use the builtin `createFrom...` methods or you use the serializer introduced in 4.8.0.
With the latter, it is required to installed [extra dependencies](https://github.com/web-auth/webauthn-framework/blob/4.9.x/src/webauthn/composer.json#L52-L55).
