### ISSUE TITLE
Cannot have login forms with mandatory fields anymore

### ISSUE THREAD

**Issue by fritzmg** [web-auth/webauthn-framework#651]
### Version(s) affected

5.0.0, 5.0.1

### Description

In https://github.com/web-auth/webauthn-framework/commit/cc698c616a74806f43647c786ae20d72a1926f00 the following was added:

https://github.com/web-auth/webauthn-framework/blob/99f3d1228d951035a094843de47922a03de1175e/src/stimulus/assets/src/controller.ts#L132-L137

This however means that you cannot use login forms with mandatory username and password fields for passkey authentications that do not require a username or passcode (e.g. like https://github.com/login) - at least not with the following HTML:

```html
<form method="post" data-controller="webauthn" …>
  <div>
    <label for="username">Username</label>
    <input type="text" name="username" id="username" autocomplete="username" placeholder="Username" required>
  </div>
  <div>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" autocomplete="current-password" placeholder="Password">
  </div>
  <div>
    <button type="submit" name="login">Login</button>
    <button type="button" data-action="webauthn#signin">Login with Passkey</button>
  </div>
</form>
```

i.e. where the `data-action="webauthn#signin"` button is part of the regular login form.

Generally I think the controller should be allowed to be defined on other elements as well - not just `<form>`.

### How to reproduce

1. Create a login `<form>` with `required` username and password fields.
2. Have another `<button type="button">` for the passkey-only login alternative.
3. Register the `webauthn` stimulus controller on the `<form>` and the `webauthn#signin` action on the second button.
4. Do not fill in the form and use the passkey login button.

The browser will ask you to fill out the form and no passkey login process will be started.

### Possible Solution

I think the stimulus controller needs some form of configuration options so you can specify whether the webauthn login process relies on the username given in the form - or the passkey is or can also be the username.

**Comment by Spomky** [comment]
Hi,

What if you disable the [form validation](https://www.w3schools.com/tags/att_form_novalidate.asp)?

```html
<form method="post" data-controller="webauthn" novalidate>
  ...
</form>
```

**Comment by fritzmg** [comment]
That would not suit our purposes - however, this is no longer relevant for us anyway. It turns out the controller does not need to be registered on a `<form>` and our solution puts the button now somewhere outside a form anyway, so this can be closed :)
