### ISSUE TITLE
[Bug] Symfony migration always created

### ISSUE THREAD

**Issue by 7system7** [web-auth/webauthn-framework#654]
### Version(s) affected

5.0.1

### Description

If anybody uses the [Doctrine Migration](https://symfony.com/bundles/DoctrineMigrationsBundle/current/index.html) what is de-facto db migration tool in Symfony framework, it always creates the same migratable properties even if it was migrated before.

An example:

```php
<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241021171956 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user__webauthn_credentials ALTER public_key_credential_id TYPE TEXT');
        $this->addSql('ALTER TABLE user__webauthn_credentials ALTER trust_path TYPE JSON');
        $this->addSql('ALTER TABLE user__webauthn_credentials ALTER aaguid TYPE TEXT');
        $this->addSql('ALTER TABLE user__webauthn_credentials ALTER credential_public_key TYPE TEXT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user__webauthn_credentials ALTER public_key_credential_id TYPE TEXT');
        $this->addSql('ALTER TABLE user__webauthn_credentials ALTER trust_path TYPE JSON');
        $this->addSql('ALTER TABLE user__webauthn_credentials ALTER aaguid TYPE TEXT');
        $this->addSql('ALTER TABLE user__webauthn_credentials ALTER credential_public_key TYPE TEXT');
    }
}
```

Meanwhile the properties are exists

![image](https://github.com/user-attachments/assets/e32f9d87-3e23-4da6-8297-39f958398f3f)

### How to reproduce

1. Create a new Symfony project
2. Set up the whole project - in my case, the db is PostgreSQL (Maybe it is an important info.)
3. Create the `PublicKeyCredentialSource` as [your docs](https://webauthn-doc.spomky-labs.com/symfony-bundle/entities-with-doctrine#the-doctrine-entity) says
4. Install the Doctrine Migration Bundle
  ```bash
  $ composer require doctrine/doctrine-migrations-bundle "^3.0"
  ```
5. Create the migration
  ```bash
  $ bin/console doctrine:migrations:diff
  ```
6. Do the migration
  ```bash
  $ bin/console doctrine:migrations:migrate --no-interaction
  ```
7. **Create a new migration the same way as above. It will creates the wrong migration sql-s.**

### Possible Solution

There was an almost similar problem w/ the PostgreSQL. (Because the schema creation.) The issue is [here](https://github.com/doctrine/dbal/issues/1110). Maybe it can help to investigate the problem.

**Comment by Spomky** [comment]
Hi,

This is not an issue related to the webauthn suite.
As it is written in the generated file, "Please modify to your needs!"
This is just one line to remove. This is a good opportunity to review the migration file to ensure it is fine.

**Comment by 7system7** [comment]
Actually it is **8 lines** of code. It is not a normal mechanism on this migration bundle that, got the same migration messages over and over. After a successful migration, the entity mapping and the database should match each other. So, the problem comes from your `PublicKeyCredentialSource`'s mapping. **It is wrong by-design.**

```bash
$ bin/console doctrine:schema:validate -v

Mapping
-------

                                                                                                                        
 [OK] The mapping files are correct.                                                                                    
                                                                                                                        

Database
--------

                                                                                                                        
 [ERROR] The database schema is not in sync with the current mapping file.                                              
                                                                                                                        

 // 4 schema diff(s) detected:                                                                                          

     ALTER TABLE user__webauthn_credentials ALTER public_key_credential_id TYPE TEXT;
     ALTER TABLE user__webauthn_credentials ALTER trust_path TYPE JSON;
     ALTER TABLE user__webauthn_credentials ALTER aaguid TYPE TEXT;
     ALTER TABLE user__webauthn_credentials ALTER credential_public_key TYPE TEXT;
```

But sorry, I will not argue more somebody who spent ~21 seconds for investigation. Good luck for more.
