### ISSUE TITLE
Include tests directories in .gitattributes

### ISSUE THREAD

**Issue by reedy** [web-auth/webauthn-framework#72]
Following on from #71... Can we get the tests directories added to the .gitattributes file too?

Thanks!

**Comment by Spomky** [comment]
Hi @reedy,

Sure I will manage that. 
At the moment I am updating the project to be fully compliant with the specification. 
I will add the missing gitattributes files and deploy to other packages within the next weeks.

**Comment by Spomky** [comment]
Done in e3ae5aad9b64c7c35d240b074a7452ee1b886240.
Will be part on the next minor version (v2.1)

**Comment by reedy** [comment]
Thanks!
