### ISSUE TITLE
rpId mismatch / DOMException

### ISSUE THREAD

**Issue by Cirrusware** [web-auth/webauthn-framework#76]
I have an issue concerning register challenge.

When I use this challenge, I have an error "rpId mismatch" (check registration)
{"rp":{"name":"xxxxx"},"pubKeyCredParams":[{"type":"public-key","alg":-7}],"challenge":"XXXXXXXXXXXXX","attestation":"direct","user":{"name":"name","id":"XXXXXXID=","displayName":"XXXX XXXX"},"authenticatorSelection":{"requireResidentKey":false,"userVerification":"preferred"},"extensions":{"loc":true},"timeout":20000}

When I use this challenge with rpId, I have a DOMException during  navigator.credentials.create(publicKey).
{"rp":{"name":"xxxxx","id":"xxxxx.net"},"pubKeyCredParams":[{"type":"public-key","alg":-7}],"challenge":"XXXXXXXXXXXXX","attestation":"direct","user":{"name":"name","id":"XXXXXXID=","displayName":"XXXX XXXX"},"authenticatorSelection":{"requireResidentKey":false,"userVerification":"preferred"},"extensions":{"loc":true},"timeout":20000}

Have you an idea ?

**Desktop/Smartphone (please complete the following information):**
 - Device: Smartphone
 - OS: Android
 - Browser: Chrome
 - Version: 76

**Comment by Cirrusware** [comment]
rpId must be equal to host.

Ex: https://www.domain.net => rpId = www.domain.net => Works
https://www.domain.net => rpId = api.domain.net => d'ont work

**Comment by Spomky** [comment]
Hi,

Either you don’t set the rpId i.e. the current domain is used or you set it on both attestation and assertion options.

I can see in the first options object it is not set (`"rp":{"name":"xxxxx"}`) but it is in the other one (`"rp":{"name":"xxxxx","id":"xxxxx.net"}`). This may be the reason for the exception.

I recommend to always set the domain to avoid any trouble. In your case and as you may have requests from `www.domain.net` or `api.domain.net`, you should set `domain.net` (`"rp":{"name":"xxxxx","id":"domain.net"}`)

**Comment by Cirrusware** [comment]
Ok thanks for this precision.
WebAuthn is now activated on my website. Thanks for your work.

I search a way to have only fingerprint without screen lock.
I read this
https://stackoverflow.com/questions/57279094/js-webauthn-how-to-disable-or-detect-screen-lock-pin-code-option
So maybe in the next release of Chrome.

Have a nice day :-)

**Comment by Spomky** [comment]
As noted in the SO question, the [uvm extension](https://www.w3.org/TR/webauthn/#sctn-uvm-extension) is the way to go.
When available, you should only need an [extension handler](https://github.com/web-auth/webauthn-framework/blob/master/doc/webauthn/PublicKeyCredentialCreation.md#extension-output-checker-handler) and reject if other methods than fingerprint are present.
