### ISSUE TITLE
Missing ramsey/uuid dependency

### ISSUE THREAD

**Issue by ralfbecker** [web-auth/webauthn-framework#86]
**Describe the bug**
web-authn/webauth-lib requires ramsey/uuid, but it is not required in composer.json

**To Reproduce**
Should be obvious.

Ralf

**Comment by Spomky** [comment]
Hi @ralfbecker,

You are right I missed that dep in composer.json.
I've just fixed it in the main package (see https://github.com/web-auth/webauthn-framework/commit/497f25a0997a2b96a99950fbae768098aff0e33b) and this will be tagged and deployed in web-auth/webauthn-lib in few hours.

**Comment by ralfbecker** [comment]
Thanks :)
