### ISSUE TITLE
Documentation examples are lacking

### ISSUE THREAD

**Issue by ralfbecker** [web-auth/webauthn-framework#87]
**Describe the bug**
The documentation examples for web-auth/webauthn-lib miss a couple of things and are wrong in some areas. 

In the process of implementing WebAuthn for [EGroupware](https://github.com/EGroupware/egroupware) I created a self-contained example app:
https://github.com/ralfbecker/webauthn

I'm happy to contribute it to this project, to save everyone finding and fixing the problems themself.

Here is a list of the problems I run into:

1. to transfer the $publicKeyCredentialCreationOptions from registration or $publicKeyCredentialCreationOptions from login to JavaScript/Browser you use json-encode, which serializes some attributes of the object as base64url and then use window.btoa to decode it again. base64url is not base64 and every couple of requests you get an error trying to decode it. I added a base64url2base64 method to your example code:
https://github.com/ralfbecker/webauthn/blob/master/register.php#L84

2. Storing the state ($publicKeyCredentialCreationOptions or $publicKeyCredentialCreationOptions objects) in the session is missing

3. No Example for the PublicKeyCredentialsRepo, I added one: https://github.com/ralfbecker/webauthn/blob/master/src/PubkeyCredentialsRepo.php

4. There were a couple more small things and typos I fixed to get a working example.

5. According to https://www.w3.org/TR/webauthn/#conforming-authenticators-u2f u2f token return no userHandle, but the $authenticatorAssertionResponseValidator->check() method requires it. I temporarily worked around it in the example code, as my Yubico Security Key - U2F and Fido2, did not return the userHandle (neither with Chrome nor Firefox): https://github.com/ralfbecker/webauthn/blob/master/login_response.php#L98
Maybe this needs an option to allow this in the check ...

Ralf

**Comment by Spomky** [comment]
Hi Ralf,

1. Indeed the doc is not in line with the last version of the library. **I will fix that asap**. The [demo](https://github.com/web-auth/symfony-demo/blob/master/assets/app/views/LoginPage/LoginPage.jsx#L92-L94) is. This is due to the last changes merged in v2 branch to pass the compliance test with the FIDO Alliance tool.

2. I am not sure where the information is missing. I will move [the note](https://github.com/web-auth/webauthn-framework/blob/v2.1/doc/webauthn/PublicKeyCredentialCreation.md#example) at the end of the example. Or maybe re-write the whole page. I am opened to any suggestion

3. OK. I will add some examples. In the Symfont package, there is [an example using Doctrine](https://github.com/web-auth/webauthn-framework/blob/v2.1/src/symfony/src/Repository/PublicKeyCredentialSourceRepository.php). What technologies do you think I could add? Plain SQL? filesystem?

4. Do not hesitate to submit a PR for that. As I am not English native, I certainly made mistakes in the doc or the source code.

5. In v2.0 and v2.1 branches, the user handle is not required. The last argument of [`check` method](https://github.com/web-auth/webauthn-framework/blob/master/src/webauthn/src/AuthenticatorAssertionResponseValidator.php#L72) allows `null` (`?string $userHandle`). But it looks like it will also throw an exception in other parts of the code. Could you please send me some sample data to correctly manage that use case?

**Comment by Spomky** [comment]
> The documentation examples for web-auth/webauthn-lib miss a couple of things and are wrong in some areas.
>
>In the process of implementing WebAuthn for EGroupware I created a self-contained example app:
https://github.com/ralfbecker/webauthn
>
>I'm happy to contribute it to this project, to save everyone finding and fixing the problems themself.

I am very happy to see this library helps you in your projects.
When I started to develop this library, I was far from imagining it to be used in so many web apps.
I would like to provide an easy to use library and I am aware of its lack of documentation, example and clarity.
Be sure that I will do my best to made it clear and simple. Please note that apart from few bugs including the ones you spotted out, this library is nearly fully compliant with the specification (see https://github.com/web-auth/webauthn-framework/issues/67) and passes almost all FIDO Alliance tests required by the certification program.

Regards.

**Comment by ralfbecker** [comment]
Hi Florent, 
1. ok, the base64UrlDecode function should go to the examples too
2. the information is there as a comment: It is important to store this request (variable $publicKeyCredentialCreationOptions) in the session for the next step. I would add the files to create a working example in the repo, beside your explanation as md file. 
3. I created a simple json file as repo-example: https://github.com/ralfbecker/webauthn/blob/master/src/PubkeyCredentialsRepo.php
4. If you agree, I'm happy to create a pull request fixing the docu-mentation with the above points and adding the full example files in a sub-directory.
5. I'm not talking about passing the user to the check method, that is already an optional parameter. I'm talking about the browser not returning the userHandle as part of the navigator.credentials.get request (https://github.com/ralfbecker/webauthn/blob/master/login.php#L91). The existence of a non-empty userHandle in the browser response is checked and fails: https://github.com/web-auth/webauthn-framework/blob/master/src/webauthn/src/AuthenticatorAssertionResponseValidator.php#L95
Ralf

**Comment by Spomky** [comment]
Hi Ralf

Please find attached the example in your repository I’ve fixed.
It uses at least the v2.1 that introduced a `Server` class that ease the creation of the webauthn server you want to build.

I think I will use this example as an official demo. There are a couple of modifications to perform, but it seems to work fine. It is online at https://dw.spomky-labs.com/register.php

Feel free to submit any PR you want, especially if it fix typos.

Regarding the user handle and the line [#95](https://github.com/web-auth/webauthn-framework/blob/master/src/webauthn/src/AuthenticatorAssertionResponseValidator.php#L95) you mention, this is the expected process described in [the section 7.2, §2](https://www.w3.org/TR/webauthn/#verifying-assertion) of the sepcification.

There are 2 use cases when a user wants to log in:
1. You know the user and you have its userHandle (e.g. you asked for his username or it is already authenticated and you want to loqin again before a critical operation)
2. You don’t know the user and don’t have its userHandle

The use case 2 __is only possible if authentication is required (default is `preferred`) and the registered authenticator is registered with a resident key (default to `false`)__. This use case is only available for some FIDO2 compatible authenticators (with PIN, fingerprint, face regognition…) that return a userHandle. The nice addition is that you can authenticate users without username (pretty cool right!).
I will create another demo with that use case.

The use case 1 is for all other authenticators (including all U2F only) and when the authentication is not required or there is no resident key.

[demo.zip](https://github.com/web-auth/webauthn-framework/files/3562481/demo.zip)

**Comment by ralfbecker** [comment]
Hi Florent,
I updated my repo with your changes, thought the helpers.js are not used, so I removed them.
The problem 5. with the empty userHandle is gone now :)
Let me know if you want me to fix the docu with what you send me. Then I'll send you a pull request.
Ralf

**Comment by Spomky** [comment]
That’s great.
Here is an example without user for the login step: [demo-login-without-user-info.zip](https://github.com/web-auth/webauthn-framework/files/3562742/demo-login-without-user-info.zip).
As you may notice, during the registration process, a resident key is asked (second argument of the `AuthenticatorSelectionCriteria` object) and the user verification is required during the registration and the login.
This will normally work with all authenticators able to manage resident keys and user verification (W10+EDGE, Android, keys with PIN/fingerprint reader…).
The demo at https://dw.spomky-labs.com/register.php now uses this configuration.

I keep this issue opened to remind me the doc needs to be updated.
Do not hesitate to ask if you have other questions.

**Comment by Spomky** [comment]
Hello Ralf,

I crteaed a PR for the modification of the documentation.
Feel free to comment in #92 if you see something to modify or if it is not clear enough.

**Comment by Spomky** [comment]
I close this issue now, let’s continue in #92
