### ISSUE TITLE
Private construct method generating errors

### ISSUE THREAD

**Issue by filliph** [web-auth/webauthn-framework#93]
**Describe the bug**
```
Call to private Jose\Component\Core\AlgorithmManager::__construct() from context 'Webauthn\AttestationStatement\AndroidSafetyNetAttestationStatementSupport'
```

**To Reproduce**
Just look in `AndroidSafetyNetAttestationStatementSupport` in any decent IDE:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/9424286/64476841-c0fd5d00-d18b-11e9-98cb-1c2361c57656.png">

**Comment by Spomky** [comment]
Hi,

It looks like you installed v1.x of the `web-token/*` library.
Actually this library requires v2.x. 

I have to admit this is not clearly mentioned in the documentation or in the `suggest` section of `composer.json`.
I will add more details in #92 to avoid any trouble like this one.

Can you confirm it works fine with web-token/* ^2.0?

**Comment by filliph** [comment]
It seems like that was the problem, the project I'm working with still uses v1.x so I used 
```
    "autoload": {
        "files": ["vendor-custom/web-token/jwt-core/AlgorithmManager.php"]
    }
```
To override the file and fix the constructor. That seems to have gotten rid of the error and the security key prompts for authorisation to see device info.

I still can't seem to get the AAGUID to save, the documentation for how to actually obtain this information is somewhat sparse.

I feel like the documentation was written for people who already have a deep knowledge and understanding of the way WebAuthn works, not people who just want something installable into their existing projects.

I'm sure I'm missing something obvious so I'll keep at it 💯

**Comment by Spomky** [comment]
> To override the file and fix the constructor. That seems to have gotten rid of the error and the security key prompts for authorisation to see device info.

Excellent!

> I feel like the documentation was written for people who already have a deep knowledge and understanding of the way WebAuthn works, not people who just want something installable into their existing projects.

That’s right. And that’s why I introduced the [simple `Server` class](https://github.com/web-auth/webauthn-framework/files/3562553/demo.zip)) to create your webauthn server and avoid all these class instances.


```php
<?php

use Webauthn\MetadataService\SimpleMetadataStatementRepository;
use Webauthn\Server;
use Webauthn\PublicKeyCredentialRpEntity;

$rpEntity = new PublicKeyCredentialRpEntity('Webauthn Server', 'my.domain.com');
$publicKeyCredentialSourceRepository = …; //Your repository here. Must implement Webauthn\PublicKeyCredentialSourceRepository

$server = new Server(
    $rpEntity,                            // The relaying party (your application)
    $publicKeyCredentialSourceRepository, // The credential repository
    null                                  // The metadata statement service (not used here)
);
```

The re-write of the documentation is ongoing.

> I still can't seem to get the AAGUID to save, the documentation for how to actually obtain this information is somewhat sparse.

The AAGUID is sent by the authenticator and for some reasons it can be null bytes (non-FIDO2 authenticator, `none` or `indirect` conveyance mode…)
Why is this information important for you?
