### ISSUE TITLE
Invalid certificate or certificate chain. unable to get local issuer certificate

### ISSUE THREAD

**Issue by filliph** [web-auth/webauthn-framework#94]
**Describe the bug**
When I add `SimpleMetadataStatementRepository` to the server and the browser requests the security key data, it fails with 

> Invalid certificate or certificate chain. Error is: C = SE, O = Yubico AB, OU = Authenticator Attestation, CN = Yubico U2F EE Serial 61730834 error 20 at 0 depth lookup: unable to get local issuer certificate

If I do not provide a MDS Repository, the key registers correctly.

```
$metadataRepo = new SimpleMetadataStatementRepository(new FilesystemAdapter('__test__));

return new Server($rpEntity, $repo, $metadataRepo);
```

Manually executing the validation via `openssl verify` also does not work:
```
openssl verify -verbose /tmp/webauthn-leaf-1sYuxD
error /tmp/webauthn-leaf-1sYuxD: verification failed
C = SE, O = Yubico AB, OU = Authenticator Attestation, CN = Yubico U2F EE Serial 61730834
error 20 at 0 depth lookup: unable to get local issuer certificate
```

EDIT: I should point out that `openssl verify -verbose /tmp/webauthn-leaf-1sYuxD` is literally the full extent of the command that is being passed to Symfony's `Process` class. There is no `webauthn-untrusted-` or `webauthn-ca-` file.

`cat`'ing the file shows 
```
-----BEGIN CERTIFICATE-----
<the key>
-----END CERTIFICATE-----
```

**Expected behavior**
I expect to not receive that error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 76

**Additional context**
I'm running the web server in a Docker container using `FROM php:7.3.9-apache-stretch`. I have checked `/etc/ssl/certs` and it contains a bunch of certificates. I have also tried to manually download the `curl.haxx.se` PEM file and set that as `-CAfile` when testing the `openssl verify` command but that also does not work.

**Comment by Spomky** [comment]
> When I add SimpleMetadataStatementRepository to the server and the browser requests the security key data, it fails with […] If I do not provide a MDS Repository, the key registers correctly.

MDS repository has been introduced in v2.1 and is optional to avoid any BC break with v2.0.
When set, all Attestation Statement support classes (except `none`) will try to find the medetata statement for the given authenticator and verify that attestation trust path.

Unfortunately, the best source is the FIDO2 MDS service but does not contain all authenticator statements. Thus this MDS repository have to be populated with lot of other services/custom sources. That’s another reason for it to be an option.

In general I don’t recommend the use of authenticators statements unless you really need it. Not only because it reduces the user privacy, but also because at the moment it is not really possible to be sure you will support all authenticator statements.

If you really want to support Yubico authenticators with the MDS repository, you still can add it:

```php
$yubicoStatement = '{"description": "Yubico U2F Root CA Serial 457200631","aaguid": "f8a011f3-8c0a-4d15-8006-17111f9edc7d","protocolFamily": "fido2","attestationRootCertificates": ["MIIDHjCCAgagAwIBAgIEG0BT9zANBgkqhkiG9w0BAQsFADAuMSwwKgYDVQQDEyNZdWJpY28gVTJGIFJvb3QgQ0EgU2VyaWFsIDQ1NzIwMDYzMTAgFw0xNDA4MDEwMDAwMDBaGA8yMDUwMDkwNDAwMDAwMFowLjEsMCoGA1UEAxMjWXViaWNvIFUyRiBSb290IENBIFNlcmlhbCA0NTcyMDA2MzEwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/jwYuhBVlqaiYWEMsrWFisgJ+PtM91eSrpI4TK7U53mwCIawSDHy8vUmk5N2KAj9abvT9NP5SMS1hQi3usxoYGonXQgfO6ZXyUA9a+KAkqdFnBnlyugSeCOep8EdZFfsaRFtMjkwz5Gcz2Py4vIYvCdMHPtwaz0bVuzneueIEz6TnQjE63Rdt2zbwnebwTG5ZybeWSwbzy+BJ34ZHcUhPAY89yJQXuE0IzMZFcEBbPNRbWECRKgjq//qT9nmDOFVlSRCt2wiqPSzluwn+v+suQEBsUjTGMEd25tKXXTkNW21wIWbxeSyUoTXwLvGS6xlwQSgNpk2qXYwf8iXg7VWZAgMBAAGjQjBAMB0GA1UdDgQWBBQgIvz0bNGJhjgpToksyKpP9xv9oDAPBgNVHRMECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBBjANBgkqhkiG9w0BAQsFAAOCAQEAjvjuOMDSa+JXFCLyBKsycXtBVZsJ4Ue3LbaEsPY4MYN/hIQ5ZM5p7EjfcnMG4CtYkNsfNHc0AhBLdq45rnT87q/6O3vUEtNMafbhU6kthX7Y+9XFN9NpmYxr+ekVY5xOxi8h9JDIgoMP4VB1uS0aunL1IGqrNooL9mmFnL2kLVVee6/VR6C5+KSTCMCWppMuJIZII2v9o4dkoZ8Y7QRjQlLfYzd3qGtKbw7xaF1UsG/5xUb/Btwb2X2g4InpiB/yt/3CpQXpiWX/K4mBvUKiGn05ZsqeY1gx4g0xLBqcU9psmyPzK+Vsgw2jeRQ5JlKDyqE0hebfC1tvFu0CCrJFcw=="]}';

$mdsRepository->addSingleStatement('yubico', new SingleMetadata(
    $yubicoStatement,
    false
));

```

**Comment by filliph** [comment]
I see, it was not clear at all from the documentation that adding statements was _required_ for the operation of the MDS, nor that it was only possible to obtain AAGUID data if you perform this extra set of validation. 

The W3 spec is also quite dense, though reading it again now with the added information from your post it makes sense: The AAGUID is only meant to be used to verify. 
This feeds into the question from the other issue; when reading the spec I was given to understand that storing the AAGUID would let me construct statistics of which security devices were the most popular, something I believe the users of my project would have liked. That was a fundamental misunderstanding of the purpose of the AAGUID on my part.

I would rather have the ability to support any current & future key with minimal upkeep, rather than having to worry about verification and needing to keep up to date with various CA's as new key vendors or platforms get added.

I really appreciate you taking the time to respond 👍

**Comment by Spomky** [comment]
Hi @filliph,

I decided to completely rewrite the documentation to make it clear for you and other developers.
You will find the first pages at https://webauthn-doc.spomky-labs.com (most of them are empty at the moment).

The specification is dense and also refers to other documents that are even more complex.
You can have an overview of [all specs here](https://fidoalliance.org/specifications/download/).

It could be a good idea to have statistics about the devices used on your application. It is possible to do it with v2.x if you don't set any Attestation Statement Repository and with the `direct` conveyance mode.
The drawback are:
* If the trust path contains certificates, they won't be fully verified,
* This reduces the user privacy as the devices have to provide data that uniquely identify the authentication and thus the user.
* AAGUID can be null in certain circumstances

In v3.0, the Attestation Statement Repository will be mandatory for all attestation types (except `none`).
I think I will add an option to continue the process even if no attestation statement is found and allow developers to decide what to do in this case: allow unknown authenticators or reject them.
